(function(){
'use strict';
const PROVIDERS={siliconflow:{baseUrl:'https://api.siliconflow.cn/v1',kind:'openai'},deepseek:{baseUrl:'https://api.deepseek.com',kind:'openai'},gemini:{baseUrl:'https://generativelanguage.googleapis.com/v1beta',kind:'gemini'},openai:{baseUrl:'',kind:'openai'}};
let lastMeta={};
function cleanBase(value){return String(value||'').trim().replace(/\/+$/,'')}
function providerConfig(config={}){const preset=PROVIDERS[config.provider]||PROVIDERS.openai;return {...config,baseUrl:cleanBase(config.baseUrl||preset.baseUrl),kind:preset.kind}}
function endpoint(base,path){base=cleanBase(base);path=String(path||'').replace(/^\/+/, '');if(!base)return '';if(base.endsWith('/'+path))return base;return `${base}/${path}`}
async function parseJson(res){const text=await res.text();try{return text?JSON.parse(text):{}}catch(_){return {raw:text}}}
function errorMessage(data,status){return data?.error?.message||data?.message||data?.error||data?.raw||`HTTP ${status}`}
function isGeminiTextModel(id){id=String(id||'').replace(/^models\//,'').toLowerCase();if(!id)return false;return !(/(?:^|[-_.])(image|imagen|veo|tts|live)(?:[-_.]|$)/.test(id)||/embedding/.test(id))}
function modelKindHint(config={}){const p=providerConfig(config);if(p.provider==='gemini'&&!isGeminiTextModel(p.model))return'目前選到的是圖片／影音／TTS 等非純文字模型，請改用 Gemini Flash、Flash-Lite 或其他文字輸出模型';return''}
function emptyResponseError(meta,data){const reason=meta?.finishReason||data?.promptFeedback?.blockReason||'EMPTY';const e=new Error(`模型沒有返回可顯示文字${reason?`（${reason}）`:''}`);e.code='EMPTY_AI_RESPONSE';e.finishReason=reason;e.provider=meta?.provider||'';e.model=meta?.model||'';e.data=data;return e}
async function callOpenAICompatibleDetailed(config){const {baseUrl,apiKey,model,messages,temperature=.8,maxTokens}=providerConfig(config);if(!baseUrl)throw new Error('缺少 Base URL');if(!apiKey)throw new Error('缺少 API Key');if(!model)throw new Error('尚未選擇模型');const body={model,messages:Array.isArray(messages)?messages:[],temperature};if(maxTokens!=null)body.max_tokens=maxTokens;const res=await fetch(endpoint(baseUrl,'chat/completions'),{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${apiKey}`},body:JSON.stringify(body)});const data=await parseJson(res);if(!res.ok){const e=new Error(errorMessage(data,res.status));e.status=res.status;e.data=data;e.provider=config.provider;e.model=model;throw e}const choice=data?.choices?.[0]||{},content=choice?.message?.content??choice?.text??'';const text=Array.isArray(content)?content.map(x=>x?.text||x?.content||'').join(''):String(content||'');const meta={provider:config.provider,model,finishReason:choice.finish_reason||'',usage:data?.usage||{},responseLength:text.length};lastMeta=meta;if(!text.trim())throw emptyResponseError(meta,data);return{text,meta}}
async function callOpenAICompatible(config){return (await callOpenAICompatibleDetailed(config)).text}
async function callGeminiDetailed(config){const {baseUrl,apiKey,model,messages,temperature=.8,maxTokens}=providerConfig(config);if(!apiKey)throw new Error('缺少 API Key');if(!model)throw new Error('尚未選擇模型');const hint=modelKindHint(config);if(hint){const e=new Error(hint);e.code='WRONG_MODEL_KIND';e.provider='gemini';e.model=model;throw e}const prompt=(messages||[]).map(m=>`${String(m.role||'user').toUpperCase()}:\n${m.content||''}`).join('\n\n'),generationConfig={temperature};if(maxTokens!=null)generationConfig.maxOutputTokens=maxTokens;const res=await fetch(`${cleanBase(baseUrl)}/models/${encodeURIComponent(String(model).replace(/^models\//,''))}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig})});const data=await parseJson(res);if(!res.ok){const e=new Error(errorMessage(data,res.status));e.status=res.status;e.data=data;e.provider='gemini';e.model=model;if(res.status===429)e.quota=true;throw e}const cand=data?.candidates?.[0]||{},text=(data?.candidates||[]).flatMap(x=>x?.content?.parts||[]).map(x=>x?.text||'').join('\n'),meta={provider:'gemini',model,finishReason:cand.finishReason||data?.promptFeedback?.blockReason||'',usage:data?.usageMetadata||{},responseLength:text.length};lastMeta=meta;if(!text.trim())throw emptyResponseError(meta,data);return{text,meta}}
async function callGemini(config){return (await callGeminiDetailed(config)).text}
async function listOpenAIModels(config){const {baseUrl,apiKey,provider}=providerConfig(config);if(!baseUrl)throw new Error('缺少 Base URL');if(!apiKey)throw new Error('缺少 API Key');let url=endpoint(baseUrl,'models');if(provider==='siliconflow')url+='?type=text&sub_type=chat';const res=await fetch(url,{headers:{'Authorization':`Bearer ${apiKey}`}}),data=await parseJson(res);if(!res.ok)throw new Error(errorMessage(data,res.status));return (Array.isArray(data?.data)?data.data:[]).map(x=>x?.id).filter(Boolean).sort((a,b)=>a.localeCompare(b))}
async function listGeminiModels(config){const {baseUrl,apiKey}=providerConfig(config);if(!apiKey)throw new Error('缺少 API Key');let pageToken='';const models=[];for(let i=0;i<10;i++){const q=new URLSearchParams({pageSize:'1000'});if(pageToken)q.set('pageToken',pageToken);const res=await fetch(`${cleanBase(baseUrl)}/models?${q}`,{headers:{'x-goog-api-key':apiKey}}),data=await parseJson(res);if(!res.ok)throw new Error(errorMessage(data,res.status));for(const m of data?.models||[]){if(Array.isArray(m.supportedGenerationMethods)&&!m.supportedGenerationMethods.includes('generateContent'))continue;const id=String(m?.name||'').replace(/^models\//,'');if(id&&isGeminiTextModel(id))models.push(id)}pageToken=data?.nextPageToken||'';if(!pageToken)break}return [...new Set(models)].sort((a,b)=>a.localeCompare(b))}
async function listModels(config={}){const cfg=providerConfig(config);if(cfg.provider==='none')return [];return cfg.kind==='gemini'?listGeminiModels(cfg):listOpenAIModels(cfg)}
async function callDetailed(config={}){const cfg=providerConfig(config);if(cfg.provider==='none')throw new Error('尚未設定 AI 服務商');return cfg.kind==='gemini'?callGeminiDetailed(cfg):callOpenAICompatibleDetailed(cfg)}
async function call(config={}){return (await callDetailed(config)).text}
window.OCLifeAI={PROVIDERS,call,callDetailed,callGemini,callOpenAICompatible,listModels,listGeminiModels,listOpenAIModels,providerConfig,isGeminiTextModel,modelKindHint,get lastMeta(){return lastMeta}};
})();