(function(){
'use strict';
const BUILD='20260812-5',KEY='oclife_announcement_settings_v1',SEEN_KEY='oclife_announcement_seen_version';
let feed=null,opening=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function settings(){try{return{mode:'update',...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(_){return{mode:'update'}}}
function save(patch){localStorage.setItem(KEY,JSON.stringify({...settings(),...patch}))}
function url(){const u=new URL('./announcements.json',location.href);u.searchParams.set('_t',Date.now());return u.href}
async function load(){if(feed)return feed;const r=await fetch(url(),{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);feed=await r.json();return feed}
function clearCache(){feed=null}
function keyOf(x){return x?.id||x?.version||''}
function latestItem(data){return(data?.announcements||[]).find(x=>keyOf(x)===data.latest)||(data?.announcements||[])[0]||null}
function seen(){try{return localStorage.getItem(SEEN_KEY)||''}catch(_){return''}}
function mark(key){try{localStorage.setItem(SEEN_KEY,key||BUILD)}catch(_){}}
function style(){if(document.getElementById('oc-ann-style'))return;const s=document.createElement('style');s.id='oc-ann-style';s.textContent=`#ocAnnouncementBtn{position:relative}#ocAnnouncementBtn:after{content:'';position:absolute;right:7px;top:7px;width:5px;height:5px;border-radius:50%;background:#5ec8ff;box-shadow:0 0 8px #3b9dff;opacity:var(--ann-dot,0)}.oc-ann-bg{align-items:flex-end;padding:0}.oc-ann-modal{width:min(720px,100%);max-height:92dvh;overflow:auto;border-radius:26px 26px 0 0;padding:17px 15px calc(22px + env(safe-area-inset-bottom));background:linear-gradient(180deg,rgba(241,247,255,.99),rgba(228,238,252,.99));color:#18273d}.oc-ann-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.oc-ann-head h2{font-size:19px;margin:2px 0 4px}.oc-ann-code{font:700 9px ui-monospace,SFMono-Regular,Menlo,monospace;color:#4b7fbd;letter-spacing:.14em}.oc-ann-close{width:38px;height:38px;border-radius:13px;border:1px solid #cad9ec;background:#edf4fc;color:#486786}.oc-ann-current{margin-top:13px;padding:14px;border:1px solid #c6d8ee;border-radius:17px;background:rgba(255,255,255,.72);box-shadow:0 10px 28px rgba(42,86,143,.06)}.oc-ann-current h3{font-size:16px;margin:0 0 4px}.oc-ann-date{font-size:10px;color:#7c8da4}.oc-ann-summary{font-size:12.5px;line-height:1.65;color:#4e617b;margin:8px 0}.oc-ann-list{padding-left:18px;margin:8px 0 0}.oc-ann-list li{font-size:12px;line-height:1.65;margin:4px 0}.oc-ann-pref{margin-top:12px;padding:12px;border:1px solid #cad9eb;border-radius:15px;background:rgba(244,248,253,.7)}.oc-ann-pref b{font-size:12px}.oc-ann-options{display:grid;gap:7px;margin-top:8px}.oc-ann-options label{display:flex;gap:8px;align-items:flex-start;font-size:11.5px;color:#596c84;line-height:1.5}.oc-ann-history{margin-top:15px}.oc-ann-history h3{font-size:13px;margin:0 0 8px}.oc-ann-old{padding:10px 0;border-top:1px solid #d7e2ef}.oc-ann-old button{width:100%;border:0;background:transparent;text-align:left;color:inherit;padding:0}.oc-ann-old-title{font-size:12px;font-weight:800}.oc-ann-old-meta{font-size:10px;color:#8190a4;margin-top:2px}.oc-ann-old-body{display:none;font-size:11.5px;line-height:1.6;color:#576a82;margin-top:7px}.oc-ann-old.open .oc-ann-old-body{display:block}.oc-ann-settings{margin:14px 0;padding:12px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.25)}.oc-ann-settings select{width:100%;margin-top:7px}.oc-ann-settings .toolbar{margin-top:8px}@media(min-width:700px){.oc-ann-bg{align-items:center;padding:20px}.oc-ann-modal{border-radius:24px;max-height:86dvh}}`;document.head.appendChild(s)}
function render(data){const root=document.getElementById('modalRoot'),latest=latestItem(data);if(!root||!latest)return;const k=keyOf(latest);mark(k);updateDot(false);const label=latest.type==='notice'?'SYSTEM NOTICE':`SYSTEM NOTICE // BUILD ${esc(latest.version||k)}`;root.innerHTML=`<div class="modal-bg oc-ann-bg"><div class="modal oc-ann-modal"><div class="oc-ann-head"><div><div class="oc-ann-code">${label}</div><h2>更新公告</h2><div class="oc-ann-date">${esc(latest.date||'')}</div></div><button class="oc-ann-close" id="annClose">×</button></div><section class="oc-ann-current"><h3>${esc(latest.title||'版本更新')}</h3><div class="oc-ann-summary">${esc(latest.summary||'')}</div><ul class="oc-ann-list">${(latest.items||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="oc-ann-pref"><b>公告顯示方式</b><div class="oc-ann-options"><label><input type="radio" name="annMode" value="every" ${settings().mode==='every'?'checked':''}> <span>每次進入都顯示</span></label><label><input type="radio" name="annMode" value="update" ${settings().mode==='update'?'checked':''}> <span>每次更新後第一次進入才顯示</span></label><label><input type="radio" name="annMode" value="never" ${settings().mode==='never'?'checked':''}> <span>永遠不要自動顯示</span></label></div></section><section class="oc-ann-history"><h3>近期公告</h3>${(data.announcements||[]).slice(1).map(x=>`<div class="oc-ann-old"><button type="button"><div class="oc-ann-old-title">${esc(x.title||'版本更新')}</div><div class="oc-ann-old-meta">${x.type==='notice'?'NOTICE':`BUILD ${esc(x.version||keyOf(x))}`} · ${esc(x.date||'')}</div></button><div class="oc-ann-old-body"><div>${esc(x.summary||'')}</div><ul class="oc-ann-list">${(x.items||[]).map(i=>`<li>${esc(i)}</li>`).join('')}</ul></div></div>`).join('')}</section></div></div>`;root.querySelector('#annClose').onclick=()=>root.innerHTML='';root.querySelector('.modal-bg').onclick=e=>{if(e.target===e.currentTarget)root.innerHTML=''};root.querySelectorAll('input[name="annMode"]').forEach(r=>r.onchange=()=>save({mode:r.value}));root.querySelectorAll('.oc-ann-old button').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'))}
async function open({manual=true}={}){if(opening)return;opening=true;try{style();clearCache();render(await load())}catch(e){console.warn('[OC Life] announcement:',e);if(manual)window.OCLifeAutoLife?.toast?.('公告載入失敗',{error:true})}finally{opening=false}}
function shouldAuto(data){const mode=settings().mode,latest=latestItem(data);if(!latest||mode==='never')return false;if(mode==='every')return true;return seen()!==keyOf(latest)}
function busy(){const root=document.getElementById('modalRoot');return !!(root&&root.innerHTML.trim())||!!document.getElementById('ocOnboarding')||!!document.getElementById('ocBootOverlay')||!!document.getElementById('ocUpdateOverlay')}
async function autoOpen(){try{clearCache();const data=await load();if(!shouldAuto(data)){updateDot(seen()!==keyOf(latestItem(data)));return}let tries=0;const attempt=()=>{if(!busy())return render(data);if(++tries<18)setTimeout(attempt,700)};attempt()}catch(e){console.warn('[OC Life] announcement auto:',e)}}
function updateDot(show){const b=document.getElementById('ocAnnouncementBtn');if(b)b.style.setProperty('--ann-dot',show?'1':'0')}
function ensureButton(){let b=document.getElementById('ocAnnouncementBtn');if(b)return b;b=document.createElement('button');b.id='ocAnnouncementBtn';b.className='icon-btn';b.title='更新公告';b.setAttribute('aria-label','更新公告');b.textContent='◫';const settingsBtn=document.getElementById('settingsBtn');settingsBtn?.parentNode?.insertBefore(b,settingsBtn);b.onclick=()=>open({manual:true});return b}
function injectSettings(){const modal=document.querySelector('#modalRoot .modal');if(!modal||modal.querySelector('h2')?.textContent!=='設定'||modal.querySelector('.oc-ann-settings'))return;const actions=modal.querySelector('.actions'),box=document.createElement('div');box.className='oc-ann-settings';const m=settings().mode;box.innerHTML=`<b>更新公告</b><div class="note">控制公告在什麼時候自動出現。</div><select id="annSettingMode"><option value="every" ${m==='every'?'selected':''}>每次進入都顯示</option><option value="update" ${m==='update'?'selected':''}>每次更新後第一次顯示</option><option value="never" ${m==='never'?'selected':''}>永遠不自動顯示</option></select><div class="toolbar"><button type="button" class="secondary" id="annOpenNow">查看更新公告</button></div>`;actions?.before(box);box.querySelector('#annSettingMode').onchange=e=>save({mode:e.target.value});box.querySelector('#annOpenNow').onclick=()=>open({manual:true})}
function install(){style();ensureButton();new MutationObserver(()=>{ensureButton();injectSettings()}).observe(document.documentElement,{childList:true,subtree:true});setTimeout(autoOpen,2600)}
window.OCLifeAnnouncements={version:'1.1.0',build:BUILD,open,settings,save,autoOpen,clearCache};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();
})();