(function(){
'use strict';
const VERSION='0.8.0',S=window.OCLifeStore,Multi=()=>window.OCLifeMultiCharacterAI;
const clean=v=>String(v??'').trim(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const MAP={add:{name:'#cn',gender:'#ocGender',age:'#ocAge',identity:'#ci',appearance:'#cap',personality:'#cp',speech:'#cs',relationships:'#cr',habits:'#ch',background:'#ocBackground',abilities:'#ocAbilities',boundaries:'#ocBoundaries',notes:'#ocNotes'},edit:{name:'#ecn',gender:'#ecg',age:'#eca',identity:'#eci',appearance:'#ecap',personality:'#ecp',speech:'#ecs',relationships:'#ecr',habits:'#ech',background:'#ecb',abilities:'#ecab',boundaries:'#ecbo',notes:'#ecn2'}};
function f(modal,mode,key){return modal.querySelector(MAP[mode]?.[key]||'__none__')}
function fill(modal,mode,data,{overwrite=false}={}){for(const [k,sel] of Object.entries(MAP[mode]||{})){const el=modal.querySelector(sel),v=clean(data?.[k]);if(!el||!v)continue;if(!overwrite&&clean(el.value))continue;el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}))}}
function currentWorldId(modal=null){
  const ctx=window.OCLifeWorldContext?.get?.();if(ctx&&S.get('worlds',ctx))return ctx;
  const phone=window.OCLifePhone?.activeWorldId;if(phone&&S.get('worlds',phone)){window.OCLifeWorldContext?.set?.(phone);return phone}
  const editingId=modal?.dataset?.characterId;if(editingId){const c=S.get('characters',editingId);if(c?.worldId){window.OCLifeWorldContext?.set?.(c.worldId);return c.worldId}}
  const editName=clean(modal?.querySelector?.('#ecn')?.value);if(editName){const matches=S.all('characters').filter(c=>Multi()?.key?Multi().key(c.name)===Multi().key(editName):c.name===editName);if(matches.length===1){window.OCLifeWorldContext?.set?.(matches[0].worldId);return matches[0].worldId}}
  const title=clean(document.querySelector('#pageTitle')?.textContent),byTitle=S.all('worlds').find(w=>w.name===title);if(byTitle){window.OCLifeWorldContext?.set?.(byTitle.id);return byTitle.id}
  const worlds=S.all('worlds');if(worlds.length===1){window.OCLifeWorldContext?.set?.(worlds[0].id);return worlds[0].id}return null
}
function editCharacter(modal){const id=modal.dataset.characterId;if(id)return S.get('characters',id);const name=clean(modal.querySelector('#ecn')?.value),wid=currentWorldId(modal);return S.all('characters',{worldId:wid}).find(c=>Multi()?.key?Multi().key(c.name)===Multi().key(name):c.name===name)||null}
function primaryFrom(result,modal,mode){const current=clean(f(modal,mode,'name')?.value),M=Multi();return result.characters.find(c=>M.key(c.name)===M.key(current))||result.characters[0]||null}
function style(){if(document.getElementById('oclife-ai-card-style'))return;const s=document.createElement('style');s.id='oclife-ai-card-style';s.textContent=`[data-oc-ai-card-helper]{margin:0 0 16px;padding:14px;border:1px solid #d9e2d9;border-radius:18px;background:#f2f6f1}[data-oc-ai-card-helper] h3{margin:0 0 5px;font-size:15px}[data-oc-ai-card-helper] p{font-size:12px;color:#7b756d;line-height:1.55}[data-ai-raw]{width:100%;min-height:145px;border:1px solid #dcd7cf;border-radius:13px;padding:11px;background:#fff}.oc-ai-bar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:9px}.oc-ai-status{font-size:12px;color:#7b756d;flex:1}.oc-ai-person{padding:9px 0;border-bottom:1px dashed #dfe5dd}.oc-ai-person b{display:block}.oc-ai-person .existing{color:#55705b}.oc-ai-person .new{color:#8a6b3f}.oc-ai-rel{font-size:12px;margin-top:5px;color:#657066}.oc-ai-preview{margin-top:10px}.oc-ai-warning{font-size:11px;color:#8a6b3f;margin-top:8px;line-height:1.5}`;document.head.appendChild(s)}
function extras(modal){if(!modal.querySelector('#cn')||modal.querySelector('#ocBackground'))return;const actions=modal.querySelector('.actions');if(!actions)return;const d=document.createElement('div');d.innerHTML=`<div class="two"><div class="field"><label>性別</label><input id="ocGender"></div><div class="field"><label>年齡</label><input id="ocAge"></div></div><div class="field"><label>背景經歷</label><textarea id="ocBackground"></textarea></div><div class="field"><label>能力／技能</label><textarea id="ocAbilities"></textarea></div><div class="field"><label>禁忌／底線</label><textarea id="ocBoundaries"></textarea></div><div class="field"><label>未分類補充</label><textarea id="ocNotes"></textarea></div>`;actions.parentNode.insertBefore(d,actions)}
function preview(result,wid){const M=Multi();return result.characters.map(c=>{const old=wid?M.find(wid,c.name):null;return`<div class="oc-ai-person"><b>${esc(c.name)} <span class="${old?'existing':'new'}">${old?'已存在・只補資料':'新角色'}</span></b><div class="meta">${esc([c.identity,c.gender,c.age].filter(Boolean).join(' · '))}</div><div>${esc(c.personality||c.relationships||'')}</div></div>`}).join('')+(result.relationshipLinks||[]).map(r=>`<div class="oc-ai-rel">${esc(r.from)} ↔ ${esc(r.to)} · ${esc(r.type||'關係')}</div>`).join('')}
function inject(modal){const title=modal.querySelector('h2');if(!title)return;const mode=modal.querySelector('#ecn')?'edit':modal.querySelector('#cn')?'add':'';if(!mode||modal.querySelector('[data-oc-ai-card-helper]'))return;style();extras(modal);const wid=currentWorldId(modal);if(wid)modal.dataset.worldId=wid;const wrap=document.createElement('section');wrap.dataset.ocAiCardHelper='1';wrap.innerHTML=`<h3>✦ AI 自動整理角色卡</h3><p>可直接貼一整對情侶或多名 OC。系統會先辨識同世界已有角色；已有角色只補空白資料，不會重新建立，也不會用 AI 結果覆蓋你原本的人設。</p><textarea data-ai-raw placeholder="把兩人的共同設定、各自設定、相處方式一起貼在這裡……"></textarea><div class="oc-ai-bar"><button type="button" class="primary" data-ai-classify>AI 自動整理</button><span class="oc-ai-status" data-ai-status></span></div><div class="oc-ai-preview hidden" data-ai-preview></div>`;title.after(wrap);let latest=null;wrap.querySelector('[data-ai-classify]').onclick=async()=>{const btn=wrap.querySelector('[data-ai-classify]'),st=wrap.querySelector('[data-ai-status]'),pv=wrap.querySelector('[data-ai-preview]');btn.disabled=true;st.textContent='正在辨識角色與關係…';try{latest=await Multi().classify(wrap.querySelector('[data-ai-raw]').value);if(!latest.characters.length)throw new Error('沒有辨識到可建立的角色');const active=modal.dataset.worldId||currentWorldId(modal);if(active)modal.dataset.worldId=active;pv.innerHTML=preview(latest,active)+`<div class="oc-ai-warning">安全套用不會刪除或縮短任何既有欄位；同名角色會視為同一人。</div><div class="oc-ai-bar"><button class="primary" data-safe-apply>安全套用</button><button class="secondary" data-overwrite-form>只替換目前表單</button></div>`;pv.classList.remove('hidden');st.textContent=`辨識到 ${latest.characters.length} 名角色`;pv.querySelector('[data-safe-apply]').onclick=()=>safeApply(modal,mode,latest,st);pv.querySelector('[data-overwrite-form]').onclick=()=>{if(!confirm('這只會替換目前正在編輯的表單欄位，不會改其他角色。確定嗎？'))return;const p=primaryFrom(latest,modal,mode);if(p)fill(modal,mode,p,{overwrite:true});st.textContent='已替換目前表單，尚未保存'};}catch(e){st.textContent='整理失敗：'+(e?.message||e)}finally{btn.disabled=false}}}
function safeApply(modal,mode,result,status){const wid=modal.dataset.worldId||currentWorldId(modal);if(!wid){status.textContent='目前世界識別失敗';return}window.OCLifeWorldContext?.set?.(wid);const M=Multi(),primary=primaryFrom(result,modal,mode);if(!primary){status.textContent='找不到目前角色';return}fill(modal,mode,primary,{overwrite:false});if(mode==='edit'){const current=editCharacter(modal);const made=M.apply(wid,result,{primaryId:current?.id||null,primaryName:primary.name});status.textContent=`安全合併完成：${made.map(c=>c.name).join('、')}`;return}const secondaries=M.createSecondaries(wid,result,primary.name);modal.__ocPendingMulti={result,primaryName:primary.name,worldId:wid};status.textContent=secondaries.length?`已建立／補充另一位：${secondaries.map(c=>c.name).join('、')}；保存目前角色後自動連結關係`:'已整理目前角色；保存後建立關係'}
document.addEventListener('click',e=>{const btn=e.target.closest('#charSave');if(!btn)return;const modal=btn.closest('.modal'),pending=modal?.__ocPendingMulti;if(!pending)return;const formName=clean(modal.querySelector('#cn')?.value)||pending.primaryName,stamp=Date.now();setTimeout(()=>{const chars=S.all('characters',{worldId:pending.worldId}).filter(c=>(c.createdAt||0)>=stamp-2500);const primary=chars.find(c=>Multi().key(c.name)===Multi().key(formName))||Multi().find(pending.worldId,formName);if(!primary)return;Multi().apply(pending.worldId,pending.result,{primaryId:primary.id,primaryName:pending.primaryName});window.dispatchEvent(new CustomEvent('oclife:characters-linked',{detail:{primaryId:primary.id}}))},40)},true);
function scan(){document.querySelectorAll('#modalRoot .modal').forEach(inject)}const ob=new MutationObserver(scan);ob.observe(document.documentElement,{childList:true,subtree:true});scan();window.OCLifeCharacterCardAI={version:VERSION,injectHelper:inject,safeApply,currentWorldId};
})();