(function(){
'use strict';
const VERSION='0.5.0',S=window.OCLifeStore,Multi=()=>window.OCLifeMultiCharacterAI;
const ROOT='oclife-ai-card-helper',clean=v=>String(v??'').trim(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const MAP={add:{name:'#cn',gender:'#ocGender',age:'#ocAge',identity:'#ci',appearance:'#cap',personality:'#cp',speech:'#cs',relationships:'#cr',habits:'#ch',background:'#ocBackground',abilities:'#ocAbilities',boundaries:'#ocBoundaries',notes:'#ocNotes'},edit:{name:'#ecn',gender:'#ecg',age:'#eca',identity:'#eci',appearance:'#ecap',personality:'#ecp',speech:'#ecs',relationships:'#ecr',habits:'#ech',background:'#ecb',abilities:'#ecab',boundaries:'#ecbo',notes:'#ecn2'}};
function field(modal,mode,key){return modal.querySelector(MAP[mode]?.[key]||'__none__')}
function fill(modal,mode,key,value,only){const el=field(modal,mode,key);if(!el||!value||(only&&clean(el.value)))return;el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}))}
function applyOne(modal,mode,c,only=false){Object.keys(MAP[mode]).forEach(k=>fill(modal,mode,k,c[k],only))}
function style(){if(document.getElementById('oclife-ai-card-style'))return;const s=document.createElement('style');s.id='oclife-ai-card-style';s.textContent=`[data-oc-ai-card-helper]{margin:0 0 16px;padding:14px;border:1px solid #d9e2d9;border-radius:18px;background:#f2f6f1}[data-oc-ai-card-helper] h3{margin:0 0 5px;font-size:15px}[data-oc-ai-card-helper] p{font-size:12px;color:#7b756d;line-height:1.5}[data-ai-raw]{width:100%;min-height:140px;border:1px solid #dcd7cf;border-radius:13px;padding:11px;background:#fff}.oc-ai-bar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:9px}.oc-ai-status{font-size:12px;color:#7b756d;flex:1}.oc-ai-person{padding:9px 0;border-bottom:1px dashed #dfe5dd}.oc-ai-person b{display:block}.oc-ai-rel{font-size:12px;margin-top:5px;color:#657066}.oc-ai-preview{margin-top:10px}`;document.head.appendChild(s)}
function extras(modal){if(!modal.querySelector('#cn')||modal.querySelector('#ocBackground'))return;const actions=modal.querySelector('.actions');if(!actions)return;const d=document.createElement('div');d.innerHTML=`<div class="two"><div class="field"><label>性別</label><input id="ocGender"></div><div class="field"><label>年齡</label><input id="ocAge"></div></div><div class="field"><label>背景經歷</label><textarea id="ocBackground"></textarea></div><div class="field"><label>能力／技能</label><textarea id="ocAbilities"></textarea></div><div class="field"><label>禁忌／底線</label><textarea id="ocBoundaries"></textarea></div><div class="field"><label>未分類補充</label><textarea id="ocNotes"></textarea></div>`;actions.parentNode.insertBefore(d,actions)}
function worldIdFor(modal){if(modal.querySelector('#ecn')){const name=clean(modal.querySelector('#ecn').value);return S.all('characters').find(c=>c.name===name)?.worldId||null}const visibleWorld=S.all('worlds').find(w=>document.querySelector('#pageTitle')?.textContent===w.name);return visibleWorld?.id||S.all('worlds')[0]?.id||null}
function preview(result){const people=result.characters.map(c=>`<div class="oc-ai-person"><b>${esc(c.name)}</b><span class="meta">${esc([c.identity,c.gender,c.age].filter(Boolean).join(' · '))}</span><div>${esc(c.personality||c.relationships||'')}</div></div>`).join('');const rels=result.relationshipLinks.map(r=>`<div class="oc-ai-rel">${esc(r.from)} ↔ ${esc(r.to)} · ${esc(r.type||'關係')}</div>`).join('');return people+rels}
function inject(modal){const title=modal.querySelector('h2');if(!title)return;const mode=modal.querySelector('#ecn')?'edit':modal.querySelector('#cn')?'add':'';if(!mode||modal.querySelector('[data-oc-ai-card-helper]'))return;style();extras(modal);const wrap=document.createElement('section');wrap.dataset.ocAiCardHelper='1';wrap.innerHTML=`<h3>✦ AI 自動整理角色卡</h3><p>可以直接貼一整對情侶／搭檔 OC 的共同設定。若內容明確描述另一位獨立 OC，會一起建立角色卡並建立雙向關係；不會把路人或只被提到的人亂建成角色。</p><textarea data-ai-raw placeholder="把兩人的設定一起貼在這裡即可……"></textarea><div class="oc-ai-bar"><button type="button" class="primary" data-ai-classify>AI 自動整理</button><span class="oc-ai-status" data-ai-status></span></div><div class="oc-ai-preview hidden" data-ai-preview></div>`;title.after(wrap);let latest=null;wrap.querySelector('[data-ai-classify]').onclick=async()=>{const btn=wrap.querySelector('[data-ai-classify]'),st=wrap.querySelector('[data-ai-status]'),pv=wrap.querySelector('[data-ai-preview]');btn.disabled=true;st.textContent='正在辨識角色與關係…';try{latest=await Multi().classify(wrap.querySelector('[data-ai-raw]').value);if(!latest.characters.length)throw new Error('沒有辨識到可建立的角色');pv.innerHTML=preview(latest)+`<div class="oc-ai-bar"><button class="primary" data-apply-all>套用並建立關聯角色</button><button class="secondary" data-apply-empty>只填目前角色空白欄位</button></div>`;pv.classList.remove('hidden');st.textContent=`辨識到 ${latest.characters.length} 名角色`;pv.querySelector('[data-apply-empty]').onclick=()=>{applyOne(modal,mode,latest.characters[0],true);st.textContent='已填目前角色空白欄位'};pv.querySelector('[data-apply-all]').onclick=()=>{const primaryName=clean(field(modal,mode,'name')?.value)||latest.characters[0].name;applyOne(modal,mode,latest.characters.find(c=>c.name===primaryName)||latest.characters[0],false);const wid=worldIdFor(modal);if(!wid){st.textContent='請先進入一個世界再建立關聯角色';return}const primary=mode==='edit'?S.all('characters',{worldId:wid}).find(c=>c.name===primaryName):null;const made=Multi().apply(wid,latest,{primaryId:primary?.id||null,primaryName});st.textContent=`已建立／連結：${made.map(c=>c.name).join('、')}`;window.dispatchEvent(new CustomEvent('oclife:characters-linked'))};}catch(e){st.textContent='整理失敗：'+(e?.message||e)}finally{btn.disabled=false}}}
function scan(){document.querySelectorAll('#modalRoot .modal').forEach(inject)}
const ob=new MutationObserver(scan);ob.observe(document.documentElement,{childList:true,subtree:true});scan();window.OCLifeCharacterCardAI={version:VERSION,injectHelper:inject};
})();