(function(){
'use strict';
const S=window.OCLifeStore,AI=window.OCLifeAI;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').trim();
function wid(){return window.OCLifeWorldContext?.get?.()||window.OCLifePhone?.activeWorldId||null}
function cfg(){const s=S.data.settings||{};return{provider:s.provider||'none',baseUrl:s.baseUrl||'',apiKey:s.apiKey||'',model:s.model||''}}
function style(){if(document.getElementById('oc-life-events-style'))return;const s=document.createElement('style');s.id='oc-life-events-style';s.textContent=`.oc-event-page{padding-bottom:28px}.oc-event-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.oc-event-card{border:1px solid var(--line);border-radius:18px;padding:14px;margin:10px 0;background:var(--panel)}.oc-event-top{display:flex;align-items:flex-start;gap:10px}.oc-event-top .grow{flex:1}.oc-event-title{font-weight:800;font-size:16px}.oc-event-meta{font-size:12px;color:var(--muted);margin-top:3px}.oc-event-text{white-space:pre-wrap;line-height:1.65;margin-top:10px}.oc-event-tags{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.oc-event-tag{font-size:11px;padding:5px 8px;border-radius:999px;background:var(--accent-soft)}.oc-event-actions{display:flex;gap:7px;margin-top:10px}.oc-event-actions button{font-size:12px}.oc-event-important{border-color:#d9bd73}.oc-event-empty{text-align:center;padding:50px 15px;color:var(--muted)}.oc-event-modal-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.oc-event-person{display:flex;gap:8px;align-items:center;border:1px solid var(--line);border-radius:12px;padding:9px}.oc-event-person input{width:20px;height:20px}`;document.head.appendChild(s)}
function peopleNames(ids){return(ids||[]).map(id=>S.get('characters',id)?.name).filter(Boolean)}
function recentText(worldId,limit=6){return S.all('events',{worldId}).sort((a,b)=>(b.at||b.createdAt)-(a.at||a.createdAt)).slice(0,limit).map(e=>`${e.title||'事件'}：${e.text||''}`).join('\n')}
function render(){style();const worldId=wid(),w=S.get('worlds',worldId),view=document.getElementById('view');if(!worldId||!w||!view)return;document.getElementById('pageTitle').textContent='事件簿';document.getElementById('crumb').textContent=w.name;document.getElementById('worldNav')?.classList.add('hidden');const events=S.all('events',{worldId}).sort((a,b)=>(b.at||b.createdAt)-(a.at||a.createdAt));view.innerHTML=`<section class="oc-event-page"><div class="oc-event-toolbar"><button class="primary" id="eventAi">✦ AI 生成生活事件</button><button class="secondary" id="eventManual">＋ 手動新增</button></div>${events.map(e=>card(e)).join('')||'<div class="oc-event-empty">還沒有生活事件。事件會成為聊天、動態與記憶的共同背景。</div>'}</section>`;document.getElementById('eventManual').onclick=openManual;document.getElementById('eventAi').onclick=generateAI;view.querySelectorAll('[data-event-delete]').forEach(b=>b.onclick=()=>removeEvent(b.dataset.eventDelete));view.querySelectorAll('[data-event-memory]').forEach(b=>b.onclick=()=>toMemory(b.dataset.eventMemory))}
function card(e){const names=peopleNames(e.characterIds),date=new Date(e.at||e.createdAt).toLocaleString('zh-Hant',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});return`<article class="oc-event-card ${e.importance==='重要'?'oc-event-important':''}"><div class="oc-event-top"><div class="grow"><div class="oc-event-title">${esc(e.title||'生活事件')}</div><div class="oc-event-meta">${esc(date)}${names.length?' · '+esc(names.join('、')):''}</div></div><span class="oc-event-tag">${esc(e.importance||'日常')}</span></div><div class="oc-event-text">${esc(e.text||'')}</div><div class="oc-event-tags">${(e.tags||[]).map(x=>`<span class="oc-event-tag">${esc(x)}</span>`).join('')}</div><div class="oc-event-actions"><button class="secondary" data-event-memory="${e.id}">存為關係記憶</button><button class="danger" data-event-delete="${e.id}">刪除</button></div></article>`}
function modal(html){const r=document.getElementById('modalRoot');r.innerHTML=`<div class="modal-bg"><div class="modal">${html}</div></div>`;r.querySelector('.modal-bg').onclick=e=>{if(e.target===e.currentTarget)r.innerHTML=''}}
function openManual(){const worldId=wid(),cs=S.all('characters',{worldId});modal(`<h2>新增生活事件</h2><div class="field"><label>事件標題</label><input id="evTitle"></div><div class="field"><label>發生了什麼</label><textarea id="evText" style="min-height:120px"></textarea></div><div class="field"><label>參與角色</label><div class="oc-event-modal-list">${cs.map(c=>`<label class="oc-event-person"><input type="checkbox" data-ev-char value="${c.id}"><span>${esc(c.name)}</span></label>`).join('')}</div></div><div class="field"><label>重要程度</label><select id="evImportance"><option>日常</option><option>值得記住</option><option>重要</option></select></div><div class="actions"><button class="secondary" data-close>取消</button><button class="primary" id="evSave">保存事件</button></div>`);document.querySelector('[data-close]').onclick=()=>document.getElementById('modalRoot').innerHTML='';document.getElementById('evSave').onclick=()=>{const text=clean(document.getElementById('evText').value);if(!text)return alert('請寫事件內容');S.add('events',{worldId,title:clean(document.getElementById('evTitle').value)||'生活事件',text,characterIds:[...document.querySelectorAll('[data-ev-char]:checked')].map(x=>x.value),importance:document.getElementById('evImportance').value,tags:[],source:'manual',at:Date.now()});document.getElementById('modalRoot').innerHTML='';render()}}
function parse(text){let t=clean(text).replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(t)}catch(_){const m=t.match(/\{[\s\S]*\}/);if(m)return JSON.parse(m[0]);throw new Error('事件回覆格式不完整')}}
async function generateAI(){const worldId=wid(),w=S.get('worlds',worldId),cs=S.all('characters',{worldId}),c=cfg();if(!cs.length)return window.OCLifeAutoLife?.toast?.('這個世界還沒有角色',{error:true});if(c.provider==='none'||!c.apiKey||!c.model)return window.OCLifeAutoLife?.toast?.('請先設定 AI',{error:true});window.OCLifeAutoLife?.toast?.('正在生成一件新的生活事件…',{sticky:true});const profiles=cs.map(x=>`${x.name}｜${x.identity||''}｜${String(x.personality||'').slice(0,500)}｜關係：${String(x.relationships||'').slice(0,400)}`).join('\n');const recent=recentText(worldId,8);const prompt=`替OC世界生成一件自然的小型生活事件。\n世界：${w.name}\n${w.summary||''}\n角色：\n${profiles}\n近期事件：\n${recent||'無'}\n要求：不能重複近期事件；優先是能自然影響後續聊天或動態的小事，不要動不動世界毀滅或重大轉折。可以是一人事件，也可以多人事件。只能使用已存在角色名。只輸出JSON：{"title":"","text":"事件內容，1到3句","characters":["角色名"],"importance":"日常|值得記住|重要","tags":["工作","約會"]}`;try{const out=await AI.call({...c,temperature:.95,maxTokens:900,messages:[{role:'system',content:'你是OC生活事件模擬器，生成自然、連續、符合人設的小事件。'},{role:'user',content:prompt}]});const d=parse(out),ids=(d.characters||[]).map(n=>cs.find(x=>S.namesEquivalent(x.name,n))?.id).filter(Boolean);S.add('events',{worldId,title:clean(d.title)||'生活事件',text:clean(d.text),characterIds:ids,importance:['日常','值得記住','重要'].includes(d.importance)?d.importance:'日常',tags:Array.isArray(d.tags)?d.tags.slice(0,4).map(clean).filter(Boolean):[],source:'ai',at:Date.now()});window.OCLifeAutoLife?.toast?.('✓ 新生活事件已生成');render()}catch(e){window.OCLifeAutoLife?.toast?.('事件生成失敗：'+(e?.message||e),{error:true})}}
function removeEvent(id){if(!confirm('確定刪除這件生活事件？'))return;S.remove('events',id);render()}
function toMemory(id){const e=S.get('events',id);if(!e)return;const ids=e.characterIds||[];if(ids.length<2)return window.OCLifeAutoLife?.toast?.('至少需要兩名參與角色才能存成關係記憶');let n=0;for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const chat=S.ensureChat(e.worldId,ids[i],ids[j]),old=Array.isArray(chat.memories)?chat.memories:[],text=`${e.title}：${e.text}`;if(old.some(m=>(typeof m==='string'?m:m.text)===text))continue;S.update('chats',chat.id,{memories:[...old,{id:S.uid('memory'),text,createdAt:Date.now(),source:'life-event'}].slice(-40)});n++}window.OCLifeAutoLife?.toast?.(`✓ 已加入 ${n} 組關係記憶`)}
window.OCLifeEvents={version:'1.0.0',open:render,recentText,generateAI};style();
})();