(function(){
'use strict';
const S=window.OCLifeStore;
function style(){if(document.getElementById('oc-moment-tools-style'))return;const s=document.createElement('style');s.id='oc-moment-tools-style';s.textContent=`.oc-moment-delete{margin-left:auto;border:0;background:#f4e5e3;color:#a24f4b;border-radius:11px;padding:7px 10px;font-size:12px;font-weight:700}.oc-moment-tools-head{display:flex;justify-content:flex-end;margin:0 0 12px}.oc-clear-moments{border:1px solid #e2c7c3;background:#fff7f5;color:#a24f4b;border-radius:13px;padding:9px 12px;font-weight:700}`;document.head.appendChild(s)}
function worldId(){return window.OCLifeWorldContext?.get?.()||window.OCLifePhone?.activeWorldId||null}
function deleteMoment(id,card){const m=S.get('moments',id);if(!m)return;if(!confirm('確定刪除這條動態？'))return;S.remove('moments',id);card?.remove();window.OCLifeAutoLife?.toast?.('✓ 動態已刪除');const list=document.querySelectorAll('.moment-card');if(!list.length){const view=document.querySelector('#view');view?.insertAdjacentHTML('beforeend','<div class="empty"><strong>還沒有動態</strong>角色之後可以重新發佈</div>')}}
function clearAll(wid){const all=S.all('moments',{worldId:wid});if(!all.length)return window.OCLifeAutoLife?.toast?.('目前沒有動態')||alert('目前沒有動態');if(!confirm(`確定刪除這個世界的 ${all.length} 條動態？此操作不會刪角色或聊天。`))return;for(const m of all)S.remove('moments',m.id);document.querySelectorAll('.moment-card').forEach(x=>x.remove());window.OCLifeAutoLife?.toast?.('✓ 本世界動態已清空')}
function inject(){style();if(document.querySelector('#pageTitle')?.textContent!=='動態')return;const wid=worldId(),view=document.querySelector('#view');if(!wid||!view)return;if(!view.querySelector('.oc-moment-tools-head')){const head=document.createElement('div');head.className='oc-moment-tools-head';head.innerHTML='<button class="oc-clear-moments">清空本世界動態</button>';const first=view.firstElementChild;first?.after(head);head.querySelector('button').onclick=()=>clearAll(wid)}
 const moments=S.all('moments',{worldId:wid}).sort((a,b)=>b.at-a.at),cards=[...view.querySelectorAll('.moment-card')];cards.forEach((card,i)=>{const m=moments[i];if(!m)return;card.dataset.momentId=m.id;if(card.querySelector('.oc-moment-delete'))return;const btn=document.createElement('button');btn.className='oc-moment-delete';btn.textContent='刪除';const top=card.querySelector('.row');top?.appendChild(btn);btn.onclick=e=>{e.preventDefault();e.stopPropagation();deleteMoment(card.dataset.momentId,card)}})}
new MutationObserver(()=>requestAnimationFrame(inject)).observe(document.documentElement,{childList:true,subtree:true});inject();window.OCLifeMomentTools={version:'1.1.0'};
})();