(function(){
'use strict';
const S=window.OCLifeStore;
function style(){if(document.getElementById('oc-moment-tools-style'))return;const s=document.createElement('style');s.id='oc-moment-tools-style';s.textContent=`.oc-moment-delete{margin-left:auto;border:0;background:#f4e5e3;color:#a24f4b;border-radius:11px;padding:7px 10px;font-size:12px;font-weight:700}.oc-moment-tools-head{display:flex;flex-direction:column;gap:10px;margin:0 0 12px}.oc-moment-actions{display:flex;gap:8px;flex-wrap:wrap}.oc-clear-moments{border:1px solid #e2c7c3;background:#fff7f5;color:#a24f4b;border-radius:13px;padding:9px 12px;font-weight:700}.oc-moment-generate-box{border:1px solid var(--line);background:var(--panel);border-radius:16px;padding:12px}.oc-moment-generate-box b{display:block;margin-bottom:8px}.oc-moment-char-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.oc-moment-char-btn{border:1px solid var(--line);background:#fff;border-radius:13px;padding:10px;text-align:left;font-weight:700}.oc-moment-char-btn small{display:block;color:var(--muted);font-weight:400;margin-top:2px}.oc-moment-char-btn:disabled{opacity:.5}@media(min-width:700px){.oc-moment-char-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}`;document.head.appendChild(s)}
function worldId(){return window.OCLifeWorldContext?.get?.()||window.OCLifePhone?.activeWorldId||null}
function deleteMoment(id,card){const m=S.get('moments',id);if(!m)return;if(!confirm('確定刪除這條動態？'))return;S.remove('moments',id);card?.remove();window.OCLifeAutoLife?.toast?.('✓ 動態已刪除');const list=document.querySelectorAll('.moment-card');if(!list.length){const view=document.querySelector('#view');view?.insertAdjacentHTML('beforeend','<div class="empty"><strong>還沒有動態</strong>角色之後可以重新發佈</div>')}}
function clearAll(wid){const all=S.all('moments',{worldId:wid});if(!all.length)return window.OCLifeAutoLife?.toast?.('目前沒有動態')||alert('目前沒有動態');if(!confirm(`確定刪除這個世界的 ${all.length} 條動態？此操作不會刪角色或聊天。`))return;for(const m of all)S.remove('moments',m.id);document.querySelectorAll('.moment-card').forEach(x=>x.remove());window.OCLifeAutoLife?.toast?.('✓ 本世界動態已清空')}
async function generateForCharacter(characterId,btn){const c=S.get('characters',characterId);if(!c)return;const old=btn.innerHTML;btn.disabled=true;btn.innerHTML=`正在生成…<small>${c.name}</small>`;window.OCLifeAutoLife?.toast?.(`正在生成 ${c.name} 的新動態…`,{sticky:true});try{const m=await window.OCLifeSimulator.generateMomentForCharacter(characterId);if(!m)throw new Error('沒有產生有效動態');window.OCLifeAutoLife?.toast?.(`✓ ${c.name} 的新動態已生成`);document.querySelector('#worldNav [data-tab="moments"]')?.click()}catch(e){window.OCLifeAutoLife?.toast?.(`生成失敗：${e?.message||e}`,{error:true})}finally{btn.disabled=false;btn.innerHTML=old}}
function inject(){style();if(document.querySelector('#pageTitle')?.textContent!=='動態')return;const wid=worldId(),view=document.querySelector('#view');if(!wid||!view)return;if(!view.querySelector('.oc-moment-tools-head')){const cs=S.all('characters',{worldId:wid}),head=document.createElement('div');head.className='oc-moment-tools-head';head.innerHTML=`<div class="oc-moment-generate-box"><b>指定角色發動態</b><div class="oc-moment-char-grid">${cs.map(c=>`<button class="oc-moment-char-btn" data-gen-moment="${c.id}">${c.name}<small>生成這個角色的動態</small></button>`).join('')||'<span class="meta">這個世界還沒有角色</span>'}</div></div><div class="oc-moment-actions"><button class="oc-clear-moments">清空本世界動態</button></div>`;const first=view.firstElementChild;first?.after(head);head.querySelector('.oc-clear-moments').onclick=()=>clearAll(wid);head.querySelectorAll('[data-gen-moment]').forEach(btn=>btn.onclick=()=>generateForCharacter(btn.dataset.genMoment,btn))}
 const moments=S.all('moments',{worldId:wid}).sort((a,b)=>b.at-a.at),cards=[...view.querySelectorAll('.moment-card')];cards.forEach((card,i)=>{const m=moments[i];if(!m)return;card.dataset.momentId=m.id;if(card.querySelector('.oc-moment-delete'))return;const btn=document.createElement('button');btn.className='oc-moment-delete';btn.textContent='刪除';const top=card.querySelector('.row');top?.appendChild(btn);btn.onclick=e=>{e.preventDefault();e.stopPropagation();deleteMoment(card.dataset.momentId,card)}})}
new MutationObserver(()=>requestAnimationFrame(inject)).observe(document.documentElement,{childList:true,subtree:true});inject();window.OCLifeMomentTools={version:'1.2.0'};
})();