(function(){
'use strict';
const VERSION='1.0.0';
const S=window.OCLifeStore,AI=window.OCLifeAI;
const META_KEY='oclife_photo_library_meta_v1',DB_NAME='oclife_photo_library_v1',STORE='photos';
let renderQueued=false,objectUrls=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>`photo_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
const worldId=()=>window.OCLifeWorldContext?.get?.()||window.OCLifePhone?.activeWorldId||window.OCLifeApp?.worldId||null;
function loadMeta(){try{const x=JSON.parse(localStorage.getItem(META_KEY)||'[]');return Array.isArray(x)?x:[]}catch(_){return[]}}
function saveMeta(list){localStorage.setItem(META_KEY,JSON.stringify(list));window.dispatchEvent(new CustomEvent('oclife:photo-library-change'))}
function meta(id){return loadMeta().find(x=>x.id===id)||null}
function updateMeta(id,patch){const list=loadMeta(),i=list.findIndex(x=>x.id===id);if(i<0)return null;list[i]={...list[i],...patch,updatedAt:Date.now()};saveMeta(list);return list[i]}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('照片資料庫開啟失敗'))})}
async function putBlob(id,blob){const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({id,blob,updatedAt:Date.now()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
async function getBlob(id){try{const db=await openDB(),out=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(id);r.onsuccess=()=>resolve(r.result?.blob||null);r.onerror=()=>reject(r.error)});db.close();return out}catch(_){return null}}
async function deleteBlob(id){try{const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}catch(_){}}
async function photoUrl(id){if(objectUrls.has(id))return objectUrls.get(id);const blob=await getBlob(id);if(!blob)return'';const url=URL.createObjectURL(blob);objectUrls.set(id,url);return url}
function visibleFor(p,wid){if(!p||!wid)return false;const mode=p.visibilityMode||'all',ids=Array.isArray(p.worldIds)?p.worldIds:[];if(mode==='only')return ids.includes(wid);if(mode==='exclude')return !ids.includes(wid);return true}
function readAscii(view,start,len){let s='';for(let i=0;i<len;i++)s+=String.fromCharCode(view.getUint8(start+i));return s}
function exifGPS(buffer){try{const v=new DataView(buffer);if(v.getUint16(0)!==0xffd8)return null;let off=2;while(off+4<v.byteLength){if(v.getUint8(off)!==0xff){off++;continue}const marker=v.getUint8(off+1),len=v.getUint16(off+2);if(marker===0xe1&&readAscii(v,off+4,4)==='Exif'){
 const t=off+10,endian=v.getUint16(t),le=endian===0x4949;if(!le&&endian!==0x4d4d)return null;const u16=o=>v.getUint16(o,le),u32=o=>v.getUint32(o,le);const ifd0=t+u32(t+4),n=u16(ifd0);let gpsPtr=0;for(let i=0;i<n;i++){const e=ifd0+2+i*12;if(u16(e)===0x8825){gpsPtr=t+u32(e+8);break}}if(!gpsPtr)return null;const gn=u16(gpsPtr),vals={};for(let i=0;i<gn;i++){const e=gpsPtr+2+i*12,tag=u16(e),type=u16(e+2),count=u32(e+4),raw=e+8,ptr=count*(type===5?8:type===2?1:4)>4?t+u32(raw):raw;if(tag===1||tag===3)vals[tag]=String.fromCharCode(v.getUint8(ptr));if(tag===2||tag===4){const arr=[];for(let j=0;j<3;j++){const p=ptr+j*8,den=u32(p+4);arr.push(den?u32(p)/den:0)}vals[tag]=arr}}
 const cv=a=>a?.[0]+(a?.[1]||0)/60+(a?.[2]||0)/3600;if(!vals[2]||!vals[4])return null;let lat=cv(vals[2]),lon=cv(vals[4]);if(vals[1]==='S')lat=-lat;if(vals[3]==='W')lon=-lon;return{lat,lon}
 }off+=2+len}return null}catch(_){return null}}
function modal(html){const root=document.getElementById('modalRoot');if(!root)return null;root.innerHTML=`<div class="modal-bg"><div class="modal">${html}</div></div>`;root.querySelector('.modal-bg').onclick=e=>{if(e.target===e.currentTarget)root.innerHTML=''};return root}
function close(){const r=document.getElementById('modalRoot');if(r)r.innerHTML=''}
function worldChecks(selected=[]){return S.all('worlds').map(w=>`<label style="display:flex;gap:8px;align-items:center;padding:6px 0"><input type="checkbox" data-photo-world value="${esc(w.id)}" ${selected.includes(w.id)?'checked':''}><span>${esc(w.emoji||'✦')} ${esc(w.name)}</span></label>`).join('')||'<div class="note">還沒有世界</div>'}
function visibilityText(p){if((p.visibilityMode||'all')==='all')return'所有世界';const names=(p.worldIds||[]).map(id=>S.get('worlds',id)?.name).filter(Boolean);return p.visibilityMode==='only'?`僅限：${names.join('、')||'無'}`:`屏蔽：${names.join('、')||'無'}`}
async function upload(){const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const id=uid(),buf=await file.arrayBuffer(),gps=exifGPS(buf);await putBlob(id,file);const list=loadMeta();list.unshift({id,name:file.name||'照片',type:file.type||'image/jpeg',size:file.size||0,createdAt:Date.now(),visibilityMode:'all',worldIds:[],gps,locationName:gps?`GPS ${gps.lat.toFixed(5)}, ${gps.lon.toFixed(5)}`:'',sceneNote:''});saveMeta(list);editPhoto(id,true)}catch(e){alert('照片上傳失敗：'+(e?.message||e))}};input.click()}
function editPhoto(id,afterUpload=false){const p=meta(id);if(!p)return;const root=modal(`<div class="eyebrow">GLOBAL PHOTO LIBRARY</div><h2>${afterUpload?'照片已加入全域照片庫':'編輯照片'}</h2><div class="note">照片預設可在所有世界使用。GPS 只從照片本機讀取；不會在未確認前送給 AI。</div><div id="photoPreview" style="margin:10px 0"></div><div class="field"><label>顯示位置</label><input id="photoLoc" value="${esc(p.locationName||'')}" placeholder="例如：東京・新宿／家附近的咖啡廳"></div><div class="field"><label>畫面補充（給 AI 參考，可留空）</label><textarea id="photoScene" placeholder="例如：夜景、咖啡桌、剛下過雨">${esc(p.sceneNote||'')}</textarea></div><div class="field"><label>可使用範圍</label><select id="photoVis"><option value="all" ${p.visibilityMode==='all'?'selected':''}>所有世界都能使用</option><option value="exclude" ${p.visibilityMode==='exclude'?'selected':''}>所有世界，但屏蔽指定世界</option><option value="only" ${p.visibilityMode==='only'?'selected':''}>只允許指定世界</option></select></div><div id="photoWorldBox" style="display:${p.visibilityMode==='all'?'none':'block'};max-height:190px;overflow:auto;border:1px solid var(--line);border-radius:12px;padding:8px">${worldChecks(p.worldIds||[])}</div><div class="actions"><button class="secondary" id="photoCancel">關閉</button><button class="primary" id="photoSave">儲存照片設定</button></div>`);if(!root)return;photoUrl(id).then(url=>{const box=root.querySelector('#photoPreview');if(url&&box)box.innerHTML=`<img src="${url}" style="width:100%;max-height:280px;object-fit:contain;border-radius:14px">`});root.querySelector('#photoVis').onchange=e=>root.querySelector('#photoWorldBox').style.display=e.target.value==='all'?'none':'block';root.querySelector('#photoCancel').onclick=close;root.querySelector('#photoSave').onclick=()=>{const mode=root.querySelector('#photoVis').value,worldIds=[...root.querySelectorAll('[data-photo-world]:checked')].map(x=>x.value);updateMeta(id,{visibilityMode:mode,worldIds:mode==='all'?[]:worldIds,locationName:root.querySelector('#photoLoc').value.trim(),sceneNote:root.querySelector('#photoScene').value.trim()});close();queueRender();if(afterUpload&&worldId()&&visibleFor(meta(id),worldId()))openPost(id)}}
async function removePhoto(id){if(!confirm('刪除這張照片？已發布的動態文字與留言會保留，但圖片會顯示為已刪除。'))return;const list=loadMeta().filter(x=>x.id!==id);saveMeta(list);await deleteBlob(id);const url=objectUrls.get(id);if(url)URL.revokeObjectURL(url);objectUrls.delete(id);openLibrary()}
function openLibrary(){const wid=worldId(),list=loadMeta();const root=modal(`<div class="eyebrow">GLOBAL PHOTO LIBRARY</div><h2>全域照片庫</h2><div class="note">同一張照片只需要上傳一次。${wid?'目前世界只會顯示沒有被屏蔽的照片。':''}</div><div class="actions"><button class="primary" id="photoUpload">＋ 上傳照片</button><button class="secondary" id="photoClose">關閉</button></div><div id="photoLibraryGrid" style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:12px"></div>`);if(!root)return;root.querySelector('#photoUpload').onclick=upload;root.querySelector('#photoClose').onclick=close;const grid=root.querySelector('#photoLibraryGrid'),usable=wid?list.filter(p=>visibleFor(p,wid)):list;if(!usable.length)grid.innerHTML='<div class="note">目前沒有可用照片</div>';usable.forEach(async p=>{const url=await photoUrl(p.id),card=document.createElement('div');card.style.cssText='border:1px solid var(--line);border-radius:14px;padding:8px;min-width:0';card.innerHTML=`${url?`<img src="${url}" style="width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:10px">`:'<div class="note">圖片檔已遺失</div>'}<b style="display:block;margin-top:6px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(p.name||'照片')}</b><div class="note">${esc(p.locationName||'未填位置')}<br>${esc(visibilityText(p))}</div><div class="actions" style="gap:5px;flex-wrap:wrap"><button class="primary" data-use>使用</button><button class="secondary" data-edit>設定</button><button class="secondary" data-del>刪除</button></div>`;card.querySelector('[data-use]').onclick=()=>{if(!wid)return alert('請先進入一個世界');openPost(p.id)};card.querySelector('[data-edit]').onclick=()=>editPhoto(p.id);card.querySelector('[data-del]').onclick=()=>removePhoto(p.id);grid.appendChild(card)})}
function aiConfig(){const s=S.data.settings||{};return{provider:s.provider||'none',baseUrl:s.baseUrl||'',apiKey:s.apiKey||'',model:s.model||''}}
async function generateCaption(photo,wid,selectedId){const conf=aiConfig();if(conf.provider==='none'||!conf.apiKey||!conf.model)throw new Error('請先設定 API');const w=S.get('worlds',wid),chars=S.all('characters',{worldId:wid});if(!chars.length)throw new Error('這個世界沒有角色');const chosen=selectedId?chars.find(c=>c.id===selectedId):null;const profiles=chars.map(c=>`【${c.name}】身份：${c.identity||'未設定'}；性格：${c.personality||'未設定'}；習慣：${c.habits||'未設定'}；說話：${c.speech||'未設定'}`).join('\n');const prompt=`你要替 OC Life 的角色發布一條附照片的社交動態。照片本身沒有被傳給你，只能依使用者確認的地點與畫面補充判斷，不可假裝看見未提供的細節。\n【世界】${w?.name||''}\n【世界設定】${w?.summary||''}\n【位置】${photo.locationName||'未指定'}\n【照片 GPS】${photo.gps?`${photo.gps.lat}, ${photo.gps.lon}`:'無'}\n【畫面補充】${photo.sceneNote||'無'}\n【角色】\n${profiles}\n${chosen?`使用者已指定發文者：${chosen.name}。不可換人。`:'請選擇最合理會去這個地方、也最可能發這張照片的角色。若設定不合理，不要硬改角色背景。'}\n只輸出 JSON：{"character":"角色姓名","text":"自然、符合角色口吻的動態正文"}。正文不要寫動作描寫，不要說「這張照片」，不要編造畫面補充裡沒有的具體物件。`;const out=await AI.call({...conf,maxTokens:700,temperature:.75,messages:[{role:'system',content:'你是嚴格貼合角色卡的 OC 社交動態編輯，只輸出有效 JSON。'},{role:'user',content:prompt}]});let raw=String(out||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const m=raw.match(/\{[\s\S]*\}/);if(m)raw=m[0];const d=JSON.parse(raw),actor=chosen||chars.find(c=>S.namesEquivalent(c.name,d.character));if(!actor)throw new Error('AI 沒有選出有效角色');return{characterId:actor.id,text:String(d.text||'').trim()}}
function openPost(id){const p=meta(id),wid=worldId();if(!p||!wid)return;if(!visibleFor(p,wid))return alert('這張照片已在目前世界被屏蔽');const chars=S.all('characters',{worldId:wid});if(!chars.length)return alert('這個世界還沒有角色');const root=modal(`<div class="eyebrow">PHOTO MOMENT</div><h2>發布圖片動態</h2><div id="postPhotoPreview"></div><div class="field"><label>位置</label><input id="postLoc" value="${esc(p.locationName||'')}" placeholder="可在發布前修改"></div><div class="field"><label>發文角色</label><select id="postChar"><option value="">讓 AI 依位置與角色設定選擇</option>${chars.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>正文</label><textarea id="postText" placeholder="可以自己寫，也可以讓 AI 生成"></textarea></div><div class="note">AI 目前只讀取你確認的位置、GPS 與「畫面補充」，照片檔本身不會偷偷傳給模型。</div><div class="actions"><button class="secondary" id="postCancel">取消</button><button class="secondary" id="postAI">AI 選角／寫文案</button><button class="primary" id="postSend">發布</button></div>`);if(!root)return;photoUrl(id).then(url=>{if(url)root.querySelector('#postPhotoPreview').innerHTML=`<img src="${url}" style="width:100%;max-height:310px;object-fit:contain;border-radius:14px;margin-bottom:10px">`});root.querySelector('#postCancel').onclick=close;root.querySelector('#postAI').onclick=async()=>{const b=root.querySelector('#postAI'),old=b.textContent;b.disabled=true;b.textContent='生成中…';try{const local={...p,locationName:root.querySelector('#postLoc').value.trim()},d=await generateCaption(local,wid,root.querySelector('#postChar').value||null);root.querySelector('#postChar').value=d.characterId;root.querySelector('#postText').value=d.text}catch(e){alert('生成失敗：'+(e?.message||e))}finally{b.disabled=false;b.textContent=old}};root.querySelector('#postSend').onclick=()=>{const cid=root.querySelector('#postChar').value,text=root.querySelector('#postText').value.trim(),loc=root.querySelector('#postLoc').value.trim();if(!cid)return alert('請選擇發文角色，或先讓 AI 選擇');if(!text)return alert('請輸入正文');updateMeta(id,{locationName:loc});S.add('moments',{worldId:wid,characterId:cid,text,at:Date.now(),likes:[],comments:[],photoId:id,photoLocation:loc,photoGps:p.gps||null});close();document.querySelector('#worldNav [data-tab="moments"]')?.click();queueRender()}}
async function decorateCard(card,m){if(!m?.photoId||!card)return;let slot=card.querySelector('.oc-photo-moment');if(!slot){slot=document.createElement('div');slot.className='oc-photo-moment';card.querySelector('.moment-text')?.insertAdjacentElement('afterend',slot)}const p=meta(m.photoId);if(!p){slot.innerHTML='<div class="oc-photo-blocked">照片已從照片庫刪除</div>';return}if(!visibleFor(p,m.worldId)){slot.innerHTML='<div class="oc-photo-blocked">此照片已在這個世界被屏蔽</div>';return}const url=await photoUrl(m.photoId);slot.innerHTML=`${url?`<img src="${url}" alt="動態照片">`:'<div class="oc-photo-blocked">照片檔已遺失</div>'}${m.photoLocation||p.locationName?`<div class="oc-photo-location">⌖ ${esc(m.photoLocation||p.locationName)}</div>`:''}`}
function render(){renderQueued=false;if(document.getElementById('pageTitle')?.textContent!=='動態')return;const wid=worldId(),view=document.getElementById('view');if(!wid||!view)return;const toolbar=view.querySelector('.toolbar');if(toolbar&&!toolbar.querySelector('#photoMomentOpen')){const btn=document.createElement('button');btn.id='photoMomentOpen';btn.className='secondary';btn.textContent='▧ 圖片動態';btn.onclick=openLibrary;toolbar.appendChild(btn)}for(const card of view.querySelectorAll('.moment-card')){const id=card.dataset.momentId;if(!id)continue;const m=S.get('moments',id);if(m&&m.worldId===wid&&m.photoId)decorateCard(card,m)}}
function queueRender(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(render)}
function style(){if(document.getElementById('oc-photo-moment-style'))return;const s=document.createElement('style');s.id='oc-photo-moment-style';s.textContent=`.oc-photo-moment{margin-top:10px}.oc-photo-moment img{display:block;width:100%;max-height:520px;object-fit:cover;border-radius:14px;border:1px solid rgba(91,145,205,.18)}.oc-photo-location{font-size:10.5px;color:#6f88a7;margin-top:6px}.oc-photo-blocked{font-size:11px;color:#7d91aa;padding:14px;border:1px dashed rgba(91,145,205,.28);border-radius:12px;text-align:center}`;document.head.appendChild(s)}
function install(){style();new MutationObserver(queueRender).observe(document.getElementById('view')||document.body,{childList:true,subtree:true});window.addEventListener('oclife:change',queueRender);window.addEventListener('oclife:photo-library-change',queueRender);setTimeout(queueRender,250)}
window.OCLifePhotoMoments={version:VERSION,openLibrary,upload,editPhoto,openPost,visibleFor,exifGPS,render};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();
})();