(function(){
'use strict';
const VERSION='1.1.0',S=window.OCLifeStore;
const level=q=>q?.memoryLevel||'normal';
function remembered(q){return level(q)!=='none'}
function important(q){return level(q)==='important'}
function setLevel(id,value){const q=S.get('questions',id);if(!q)return null;const v=['none','normal','important'].includes(value)?value:'normal';S.update('questions',id,{memoryLevel:v});window.dispatchEvent(new CustomEvent('oclife:question-memory-change',{detail:{id,level:v}}));return v}
function label(v){return v==='none'?'○ 不記憶':v==='important'?'★ 重要記憶':'🧠 一般記憶'}
function installStyle(){if(document.getElementById('oc-question-memory-style'))return;const s=document.createElement('style');s.id='oc-question-memory-style';s.textContent='.oc-qb-memory-row{display:flex;align-items:center;gap:8px;margin:9px 0 2px;font-size:11px;color:#657d9d}.oc-qb-memory-row select{margin-left:auto;border:1px solid #cbd9eb;border-radius:10px;background:#f8fbff;color:#365372;padding:6px 8px;font-size:11px}.oc-qb-memory-toggle{border:1px solid #cbd9eb;border-radius:10px;background:#eef5fd;color:#4c6f99;padding:6px 9px;font-size:10px}';document.head.appendChild(s)}
function decorate(){installStyle();document.querySelectorAll('.oc-qb-card[data-qb-entry]').forEach(card=>{if(card.querySelector('[data-qb-memory]'))return;const id=card.dataset.qbEntry,q=S.get('questions',id);if(!q)return;const actions=card.querySelector('.oc-qb-card-actions')||card;const sel=document.createElement('select');sel.dataset.qbMemory=id;sel.className='oc-qb-memory-toggle';sel.innerHTML='<option value="none">○ 不記憶</option><option value="normal">🧠 一般記憶</option><option value="important">★ 重要記憶</option>';sel.value=level(q);sel.onchange=()=>setLevel(id,sel.value);actions.prepend(sel)})}
function composeControl(){const compose=document.querySelector('.oc-qb-compose');if(!compose||compose.querySelector('#qbMemoryLevel'))return;const actions=compose.querySelector('.oc-qb-actions');if(!actions)return;const row=document.createElement('div');row.className='oc-qb-memory-row';row.innerHTML='<span>這次回答要成為 OC 的記憶嗎？</span><select id="qbMemoryLevel"><option value="none">○ 不記憶</option><option value="normal" selected>🧠 一般記憶</option><option value="important">★ 重要記憶</option></select>';actions.before(row)}
function selectedLevel(){return document.getElementById('qbMemoryLevel')?.value||'normal'}
function longTermContext(worldId,targetIds,limit=8){const set=new Set(targetIds);return S.all('questions',{worldId}).filter(q=>important(q)&&(q.targetIds||[]).some(id=>set.has(id))).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,limit).map(q=>`問：${String(q.question||'').slice(0,220)}\n${(q.answers||[]).map(a=>`${a.name||'角色'}：${String(a.text||'').slice(0,300)}`).join('\n')}`).join('\n---\n')}
function recentContext(worldId,targetIds,limit=4){const set=new Set(targetIds);return S.all('questions',{worldId}).filter(q=>remembered(q)&&(q.targetIds||[]).some(id=>set.has(id))).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,limit).map(q=>`問：${String(q.question||'').slice(0,180)}\n${(q.answers||[]).map(a=>`${a.name||'角色'}：${String(a.text||'').slice(0,220)}`).join('\n')}`).join('\n---\n')}
function patchStore(){if(S.__questionMemoryPatched)return;S.__questionMemoryPatched=true;const add=S.add.bind(S);S.add=function(collection,data){if(collection==='questions'&&data&&!Object.prototype.hasOwnProperty.call(data,'memoryLevel'))data={...data,memoryLevel:selectedLevel()};return add(collection,data)}}
function install(){installStyle();patchStore();const root=document.getElementById('modalRoot')||document.body;new MutationObserver(()=>{composeControl();decorate()}).observe(root,{childList:true,subtree:true});window.addEventListener('oclife:change',decorate);setTimeout(()=>{composeControl();decorate()},100);window.OCLifeQuestionMemory={version:VERSION,level,remembered,important,setLevel,label,selectedLevel,recentContext,longTermContext,decorate}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();
})();