(function(){
'use strict';
const S=()=>window.OCLifeStore,AI=()=>window.OCLifeAI;const pick=a=>a[Math.floor(Math.random()*a.length)];
const T={activities:['在整理手邊的東西','剛忙完一件事，正在放空','坐著發呆','在吃東西','在看訊息','準備出門','剛回到住處','在處理工作','在做自己的興趣','什麼也沒做，只是休息'],moods:['平靜','放鬆','有點累','心情不錯','專注','有點無聊'],places:['住處','工作地點','街上','咖啡店','房間','附近']};
function chars(worldId){return S().all('characters',{worldId})}function statusOf(id){return S().all('statuses').find(s=>s.characterId===id)}
function tickStatuses(worldId){for(const c of chars(worldId)){const st=statusOf(c.id);if(!st||Math.random()<.58)continue;S().update('statuses',st.id,{place:pick(T.places),activity:pick(T.activities),mood:pick(T.moods),updatedAt:Date.now()})}}
function rel(a,b){return(a.relationshipLinks||[]).find(x=>x.characterId===b.id)||null}function cfg(){const s=S().data.settings||{};return{provider:s.provider||'none',baseUrl:s.baseUrl||'',apiKey:s.apiKey||'',model:s.model||''}}
function parseJSON(text){let t=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(t)}catch(_){const m=t.match(/\{[\s\S]*\}/);if(m)return JSON.parse(m[0]);throw new Error('AI 格式無法解析')}}
function charProfile(c){const ip=c.interactionProfile||{};return`姓名：${c.name}\n身份：${c.identity||'未設定'}\n性格：${c.personality||'未設定'}\n性格底層：${ip.core||''}\n外在表現：${ip.outer||''}\n親密關係中的樣子：${ip.intimate||''}\n情緒反應：${ip.emotionalReactions||''}\n主動性：${ip.initiative||''}\n親密表達：${ip.affection||''}\n說話方式：${c.speech||ip.speechRhythm||''}\n習慣：${c.habits||ip.physicalHabits||''}\n背景：${c.background||''}`}
function memoryText(chat){const mem=Array.isArray(chat.memories)?chat.memories:[];return mem.slice(-12).map((m,i)=>`${i+1}. ${typeof m==='string'?m:m.text||''}`).filter(Boolean).join('\n')}
function saveMemory(chat,text){text=String(text||'').trim();if(!text)return;const old=Array.isArray(chat.memories)?chat.memories:[];if(old.some(m=>String(typeof m==='string'?m:m.text||'').trim()===text))return;S().update('chats',chat.id,{memories:[...old,{id:S().uid('memory'),text,createdAt:Date.now(),source:'ai-chat'}].slice(-40)})}
async function aiChat(worldId,a,b,chat){const c=cfg();if(c.provider==='none'||!c.apiKey||!c.model)throw new Error('AI 未設定');const w=S().get('worlds',worldId),ra=rel(a,b),rb=rel(b,a),sa=statusOf(a.id),sb=statusOf(b.id),recent=S().all('messages',{chatId:chat.id}).sort((x,y)=>x.at-y.at).slice(-14).map(m=>`${S().get('characters',m.senderId)?.name||'角色'}：${m.text}`).join('\n'),memories=memoryText(chat);const prompt=`模擬兩名OC自然聊天。\n【世界】${w?.name||''}\n${w?.summary||''}\n硬規則：${w?.rules||''}\n【A】${charProfile(a)}\n現在：${sa?.place||''}｜${sa?.activity||''}｜${sa?.mood||''}\n【B】${charProfile(b)}\n現在：${sb?.place||''}｜${sb?.activity||''}｜${sb?.mood||''}\n【關係】${ra?.type||rb?.type||'未標明'}\nA看B：${ra?.perspective||''}\nB看A：${rb?.perspective||''}\n共同：${ra?.sharedFacts||rb?.sharedFacts||''}\n熟悉程度：${ra?.intimacyLevel||rb?.intimacyLevel||''}\n相處模式：${ra?.interactionStyle||rb?.interactionStyle||''}\nA對B稱呼：${ra?.nicknames||'未設定'}\nB對A稱呼：${rb?.nicknames||'未設定'}\n長期記憶：${memories||'暫無'}\n最近聊天：${recent||'暫無'}\n生成4到8則短訊息。關係熟悉度和性格要直接體現在語氣、默契、稱呼、接話方式。情侶不可像陌生人寒暄，不要解說設定。只輸出JSON：{"messages":[{"sender":"姓名","text":"訊息"}],"memory":"有長期價值的新記憶，沒有留空"}`;const out=await AI().call({...c,temperature:.88,maxTokens:2000,messages:[{role:'system',content:'高一致性OC互動模擬器。不要把不同角色寫成同一種語氣。'},{role:'user',content:prompt}]});const d=parseJSON(out);return{messages:Array.isArray(d.messages)?d.messages:[],memory:String(d.memory||'').trim()}}
async function autonomousChat(worldId){const list=chars(worldId);if(list.length<2)return null;let pairs=[];for(const a of list)for(const l of(a.relationshipLinks||[])){const b=S().get('characters',l.characterId);if(b&&b.worldId===worldId&&a.id<b.id)pairs.push([a,b])}let a,b;if(pairs.length&&Math.random()<.85)[a,b]=pick(pairs);else{a=pick(list);b=pick(list.filter(x=>x.id!==a.id))}const chat=S().ensureChat(worldId,a.id,b.id);try{const g=await aiChat(worldId,a,b,chat);if(!g.messages.length)throw new Error('空回覆');const base=Date.now()-g.messages.length*900,made=[];for(let i=0;i<g.messages.length;i++){const x=g.messages[i],sender=S().namesEquivalent(x.sender,a.name)?a:S().namesEquivalent(x.sender,b.name)?b:null;if(sender&&String(x.text||'').trim())made.push(S().add('messages',{chatId:chat.id,worldId,senderId:sender.id,text:String(x.text).trim(),at:base+i*900}))}if(g.memory)saveMemory(chat,g.memory);S().update('chats',chat.id,{lastAt:Date.now()});return made}catch(e){console.warn('[OC Life] AI chat failed:',e);return null}}
async function aiMoment(worldId,c){const conf=cfg();if(conf.provider==='none'||!conf.apiKey||!conf.model)throw new Error('AI 未設定');const w=S().get('worlds',worldId),st=statusOf(c.id),recent=S().all('moments',{worldId}).filter(m=>m.characterId===c.id).sort((a,b)=>b.at-a.at).slice(0,5).map(m=>m.text).join('\n---\n');const related=(c.relationshipLinks||[]).map(l=>{const o=S().get('characters',l.characterId);return o?`${o.name}：${l.type||'關係'}；${l.perspective||''}；稱呼${l.nicknames||''}`:''}).filter(Boolean).join('\n');const prompt=`你要替OC生成一條像真人社交平台/朋友圈的動態，而不是狀態報告。\n【世界】${w?.name||''} ${w?.summary||''}\n【角色】${charProfile(c)}\n【現在】${st?.place||''}｜${st?.activity||''}｜${st?.mood||''}\n【重要關係】${related||'無'}\n【此角色最近發過的動態】\n${recent||'暫無'}\n要求：\n1. 必須像這個角色本人會發的東西，語氣服從性格和說話方式。\n2. 不要每次都說“今天的狀態”“剛回來”“偶爾這樣也不錯”，禁止程序匯報感。\n3. 可以是隨手一句、吐槽、照片配文式文字、分享吃的/工作/天氣/愛好、含蓄提到親近的人、只有熟人才懂的話；不是每條都要有完整事件。\n4. 長短隨機，通常1到3句；角色本來話少就更短。不要替角色添加重大新設定。\n5. comments：其他角色是否會留言由關係和性格決定，不需要每條都有。留言也必須像熟人，不能客服式。\n只輸出JSON：{"text":"動態正文","comments":[{"character":"留言角色姓名","text":"留言"}]}`;const out=await AI().call({...conf,temperature:1.0,maxTokens:1200,messages:[{role:'system',content:'你是OC社交動態模擬器。寫得像真人發朋友圈，不寫角色狀態摘要。'},{role:'user',content:prompt}]});return parseJSON(out)}
async function autonomousMoment(worldId){const list=chars(worldId);if(!list.length)return null;const c=pick(list);try{const g=await aiMoment(worldId,c);const text=String(g.text||'').trim();if(!text)throw new Error('空動態');const moment=S().add('moments',{worldId,characterId:c.id,text,at:Date.now(),likes:[],comments:[]});for(const cm of(Array.isArray(g.comments)?g.comments:[])){const o=list.find(x=>S().namesEquivalent(x.name,cm.character));if(o&&o.id!==c.id&&String(cm.text||'').trim())moment.comments.push({id:S().uid('comment'),characterId:o.id,text:String(cm.text).trim(),at:Date.now()+1000})}S().save();return moment}catch(e){console.warn('[OC Life] AI moment failed:',e);return null}}
function simulate(worldId,opts={}){tickStatuses(worldId);if(opts.chat!==false&&Math.random()<.75)autonomousChat(worldId);if(opts.moment!==false&&Math.random()<.55)autonomousMoment(worldId)}
window.OCLifeSimulator={simulate,tickStatuses,autonomousChat,autonomousMoment};
})();