(function(){
'use strict';
const S=()=>window.OCLifeStore,AI=()=>window.OCLifeAI,pick=a=>a[Math.floor(Math.random()*a.length)];
const T={activities:['在整理手邊的東西','剛忙完一件事，正在放空','坐著發呆','在吃東西','在看訊息','準備出門','剛回到住處','在處理工作','在做自己的興趣','什麼也沒做，只是休息'],moods:['平靜','放鬆','有點累','心情不錯','專注','有點無聊'],places:['住處','工作地點','街上','咖啡店','房間','附近']};
const clip=(v,n=900)=>{const s=String(v||'');return s.length>n?s.slice(0,n)+'…':s};
function F(){return window.OCLifeFidelity}
function chars(worldId){return S().all('characters',{worldId})}
function statusOf(id,worldId){return S().all('statuses',{worldId}).find(s=>s.characterId===id)||S().all('statuses').find(s=>s.characterId===id)}
function tickStatuses(worldId){for(const c of chars(worldId)){const st=statusOf(c.id,worldId);if(!st||Math.random()<.58)continue;if(st.recentEventId&&Date.now()-Number(st.updatedAt||0)<3*60*60*1000)continue;S().update('statuses',st.id,{place:pick(T.places),activity:pick(T.activities),mood:pick(T.moods),updatedAt:Date.now(),withIds:[],recentEventId:null})}}
function rel(a,b){return(a.relationshipLinks||[]).find(x=>x.characterId===b.id)||null}
function cfg(){const s=S().data.settings||{};return{provider:s.provider||'none',baseUrl:s.baseUrl||'',apiKey:s.apiKey||'',model:s.model||''}}
function parseJSON(text){let t=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(t)}catch(_){const m=t.match(/\{[\s\S]*\}/);if(m){try{return JSON.parse(m[0])}catch(__){}}const pairs=[...t.matchAll(/"sender"\s*:\s*"([^"]+)"[\s\S]{0,160}?"text"\s*:\s*"((?:\\.|[^"\\])*)"/g)].map(x=>({sender:x[1],text:x[2].replace(/\\n/g,'\n').replace(/\\"/g,'"')}));if(pairs.length)return{messages:pairs,memory:''};throw new Error('AI 回覆被截斷或 JSON 格式不完整')}}
function charProfile(c,compact=false){return F()?.profile?.(c,compact)||`姓名：${c.name}\n性別：${c.gender||'未設定'}\n性格：${clip(c.personality,compact?420:1100)}\n說話：${clip(c.speech,compact?420:1100)}\n背景：${clip(c.background,compact?420:1100)}`}
function memoryText(chat,compact=false){return(Array.isArray(chat.memories)?chat.memories:[]).slice(compact?-6:-12).map((m,i)=>`${i+1}. ${clip(typeof m==='string'?m:m.text||'',compact?220:500)}`).filter(Boolean).join('\n')}
function saveMemory(chat,text,people=[]){text=F()?.sanitize?.(String(text||'').trim(),people)||String(text||'').trim();if(!text)return;const old=Array.isArray(chat.memories)?chat.memories:[];if(old.some(m=>String(typeof m==='string'?m:m.text||'').trim()===text))return;S().update('chats',chat.id,{memories:[...old,{id:S().uid('memory'),text,createdAt:Date.now(),source:'ai-chat'}].slice(-50)})}
function stripActions(text){let t=String(text||'').trim();t=t.replace(/\*[^*\n]{1,120}\*/g,'').replace(/（[^）\n]*(?:笑|看|摸|抱|親|吻|走|坐|站|靠|伸|抬|低|轉|皺|挑眉|嘆|動作|神情)[^）\n]*）/g,'').replace(/\([^\)\n]*(?:smile|look|touch|hug|kiss|walk|sit|stand|sigh)[^\)\n]*\)/gi,'');return t.replace(/\s{2,}/g,' ').trim()}
function senderFor(label,a,b,index){const raw=String(label??'').trim();if(S().namesEquivalent(raw,a.name))return a;if(S().namesEquivalent(raw,b.name))return b;const simple=raw.toLowerCase().replace(/[\s：:._\-]/g,'');if(['a','角色a','charactera','人物a','1','角色1'].includes(simple))return a;if(['b','角色b','characterb','人物b','2','角色2'].includes(simple))return b;if(simple.includes(S().canonicalName(a.name)))return a;if(simple.includes(S().canonicalName(b.name)))return b;return index%2===0?a:b}
function validateChat(chat){if(!chat)throw new Error('找不到聊天室');if(!chat.worldId)throw new Error('聊天室缺少世界資料');if(!Array.isArray(chat.memberIds)||chat.memberIds.length!==2)throw new Error('聊天室成員資料異常');const world=S().get('worlds',chat.worldId);if(!world)throw new Error('聊天室所屬世界不存在');const a=S().get('characters',chat.memberIds[0]),b=S().get('characters',chat.memberIds[1]);if(!a||!b)throw new Error('聊天室角色不存在');if(a.worldId!==chat.worldId||b.worldId!==chat.worldId)throw new Error('聊天室角色與世界不一致');return{world,a,b}}
async function aiChat(worldId,a,b,chat,compact=false){const c=cfg();if(c.provider==='none'||!c.apiKey||!c.model)throw new Error('AI 未設定');const w=S().get('worlds',worldId),ra=rel(a,b),rb=rel(b,a),sa=statusOf(a.id,worldId),sb=statusOf(b.id,worldId),recent=S().all('messages',{chatId:chat.id}).sort((x,y)=>x.at-y.at).slice(compact?-8:-14).map(m=>`${S().get('characters',m.senderId)?.name||'角色'}：${clip(m.text,compact?180:400)}`).join('\n'),memories=memoryText(chat,compact),count=compact?'3到5':'4到8',events=F()?.eventContext?.(worldId,[a.id,b.id],compact?3:6)||'',fidelity=F()?.hardRules?.([a,b])||'',relation=F()?.relation?.(a,b)||`關係：${ra?.type||rb?.type||'未標明'}`;const prompt=`模擬兩名OC在聊天軟體裡自然聊天。\n${fidelity}\n【世界】${w?.name||''}\n${clip(w?.summary,compact?500:1200)}\n硬規則：${clip(w?.rules,compact?500:1200)}\n【A】${charProfile(a,compact)}\n現在：${sa?.place||''}｜${sa?.activity||''}｜${sa?.mood||''}\n【B】${charProfile(b,compact)}\n現在：${sb?.place||''}｜${sb?.activity||''}｜${sb?.mood||''}\n${relation}\n【最近36小時事件】\n${events||'無'}\n【長期與近期記憶】\n${memories||'暫無'}\n【最近聊天】\n${recent||'暫無'}\n生成${count}則短訊息。若近期事件與這兩人有關，可以自然接續，但不要每次硬提事件。情侶、伴侶、老友等已熟識關係禁止陌生人式寒暄。只能輸出角色真正打出的文字，禁止動作、神態、心理、場景旁白。sender只能填「${a.name}」或「${b.name}」。只輸出JSON：{"messages":[{"sender":"${a.name}","text":"純聊天文字"}],"memory":"只有真正值得長期記住的新資訊才填，沒有留空"}`;const result=AI().callDetailed?await AI().callDetailed({...c,temperature:.72,maxTokens:compact?1000:1800,messages:[{role:'system',content:'高一致性OC聊天模擬器。角色卡是硬約束，劇情服務角色，不得平均化人格；嚴格遵守性別、關係、稱呼與既有記憶。只輸出有效JSON與純聊天。'},{role:'user',content:prompt}]}):{text:await AI().call({...c,temperature:.72,maxTokens:compact?1000:1800,messages:[{role:'user',content:prompt}]}),meta:{}};let d;try{d=parseJSON(result.text)}catch(e){e.aiMeta=result.meta;throw e}return{messages:Array.isArray(d.messages)?d.messages:[],memory:String(d.memory||'').trim(),meta:result.meta}}
function lengthLike(meta={}){const r=String(meta.finishReason||'').toLowerCase();return r.includes('length')||r.includes('max_token')||r==='max_tokens'}
async function generateForChat(chat){const{a,b}=validateChat(chat),worldId=chat.worldId;let g;try{g=await aiChat(worldId,a,b,chat,false);if(lengthLike(g.meta)&&!g.messages.length)throw Object.assign(new Error('輸出長度已達上限'),{retryCompact:true})}catch(e){console.warn('[OC Life] full chat generation failed; retry compact',e,e.aiMeta||'');try{g=await aiChat(worldId,a,b,chat,true)}catch(e2){const reason=e2.aiMeta?.finishReason||e.aiMeta?.finishReason||'';throw new Error(reason?`生成失敗（${reason}）：可能是角色資料或輸出超過模型限制`:`生成失敗：${e2.message||e.message}`)}}if(!g.messages.length)throw new Error('AI 回覆沒有訊息');const base=Date.now()-g.messages.length*900,made=[];for(let i=0;i<g.messages.length;i++){const x=g.messages[i],sender=senderFor(x.sender,a,b,i);let text=stripActions(x.text);text=F()?.sanitize?.(text,[a,b])||text;if(text)made.push(S().add('messages',{chatId:chat.id,worldId,senderId:sender.id,text,at:base+i*900}))}if(!made.length)throw new Error('AI 有回覆，但沒有可顯示的有效訊息');if(g.memory)saveMemory(chat,g.memory,[a,b]);S().update('chats',chat.id,{lastAt:Date.now()});return made}
async function generateChatById(chatId){return generateForChat(S().get('chats',chatId))}
async function autonomousChat(worldId){const list=chars(worldId);if(list.length<2)return null;let pairs=[];for(const a of list)for(const l of(a.relationshipLinks||[])){const b=S().get('characters',l.characterId);if(b&&b.worldId===worldId&&a.id<b.id)pairs.push([a,b])}let a,b;if(pairs.length&&Math.random()<.88)[a,b]=pick(pairs);else{a=pick(list);b=pick(list.filter(x=>x.id!==a.id))}return generateForChat(S().ensureChat(worldId,a.id,b.id))}
function normalizeMomentText(s){return String(s||'').toLowerCase().replace(/https?:\/\/\S+/g,'').replace(/[\s\p{P}\p{S}]+/gu,'')}
function ngrams(s,n=2){const x=normalizeMomentText(s),set=new Set();for(let i=0;i<=x.length-n;i++)set.add(x.slice(i,i+n));return set}
function similarity(a,b){const A=ngrams(a),B=ngrams(b);if(!A.size||!B.size)return 0;let inter=0;for(const x of A)if(B.has(x))inter++;return inter/Math.max(A.size,B.size)}
function recentMomentsFor(c,limit=8){return S().all('moments',{worldId:c.worldId}).filter(m=>m.characterId===c.id).sort((a,b)=>b.at-a.at).slice(0,limit)}
function tooSimilar(text,c){const recent=recentMomentsFor(c,8);return recent.some(m=>{const a=normalizeMomentText(text),b=normalizeMomentText(m.text);if(a===b)return true;if(a.length<10||b.length<10)return a===b;return similarity(a,b)>=0.72})}
async function aiMoment(worldId,c,retryNote=''){const conf=cfg();if(conf.provider==='none'||!conf.apiKey||!conf.model)throw new Error('AI 未設定');const w=S().get('worlds',worldId),st=statusOf(c.id,worldId),recent=recentMomentsFor(c,6).map((m,i)=>`${i+1}. ${clip(m.text,280)}`).join('\n'),related=(c.relationshipLinks||[]).map(l=>{const o=S().get('characters',l.characterId);return o&&o.worldId===worldId?`${o.name}：${l.type||'關係'}；${clip(l.perspective,700)}；稱呼${l.nicknames||''}`:''}).filter(Boolean).join('\n'),events=F()?.eventContext?.(worldId,[c.id],5)||'',fidelity=F()?.hardRules?.([c])||'';const prompt=`替OC生成一條像真人朋友圈的動態。\n${fidelity}\n世界：${w?.name||''} ${clip(w?.summary,900)}\n角色：${charProfile(c,true)}\n現在：${st?.place||''}｜${st?.activity||''}｜${st?.mood||''}\n重要關係：${related||'無'}\n最近36小時事件：${events||'無'}\n【最近發過的動態】\n${recent||'暫無'}\n硬規則：1. 必須像這個角色本人，不得平均化成通用溫柔口吻；2. 可自然受近期事件影響，但不要每次匯報事件；3. 不能重複最近動態原句或同主題換句話說；4. 不要程序匯報，不要固定使用「今天／剛剛／偶爾這樣也不錯」；5. 正文和留言禁止動作旁白。${retryNote?`\n6. 上一版內容與近期動態太相似：${retryNote}，這次必須換主題。`:''}\n只輸出JSON：{"text":"動態正文","comments":[{"character":"留言角色姓名","text":"留言"}]}`;const out=await AI().call({...conf,temperature:.82,maxTokens:1000,messages:[{role:'system',content:'高角色一致性的OC社交動態模擬器。角色卡和性別是硬約束，保留角色自己的缺點、語氣和社交習慣。'},{role:'user',content:prompt}]});return parseJSON(out)}
async function generateMomentForCharacter(characterId){const c=S().get('characters',characterId);if(!c)throw new Error('角色不存在');const worldId=c.worldId,list=chars(worldId);let g=await aiMoment(worldId,c,''),text=stripActions(g.text);text=F()?.sanitize?.(text,[c])||text;if(!text)throw new Error('空動態');if(tooSimilar(text,c)){window.OCLifeAutoLife?.toast?.('內容和近期動態太像，正在換一個主題重試…',{sticky:true});g=await aiMoment(worldId,c,clip(text,180));text=stripActions(g.text);text=F()?.sanitize?.(text,[c])||text}if(!text)throw new Error('空動態');if(tooSimilar(text,c))throw new Error('生成內容與近期動態過於相似，已取消發佈');const moment=S().add('moments',{worldId,characterId:c.id,text,at:Date.now(),likes:[],comments:[]});for(const cm of(Array.isArray(g.comments)?g.comments:[])){const o=list.find(x=>S().namesEquivalent(x.name,cm.character));let ct=stripActions(cm.text);ct=F()?.sanitize?.(ct,[o||c,c])||ct;if(o&&o.id!==c.id&&ct)moment.comments.push({id:S().uid('comment'),characterId:o.id,text:ct,at:Date.now()+1000})}S().save();return moment}
function leastRecentlyPosted(worldId){const list=chars(worldId);if(!list.length)return null;const lastMap=new Map(list.map(c=>[c.id,0]));for(const m of S().all('moments',{worldId}))if(lastMap.has(m.characterId)&&m.at>lastMap.get(m.characterId))lastMap.set(m.characterId,m.at);const sorted=list.map(c=>({c,last:lastMap.get(c.id)||0})).sort((a,b)=>a.last-b.last),min=sorted[0].last;return pick(sorted.filter(x=>x.last===min).map(x=>x.c))}
async function autonomousMoment(worldId){const c=leastRecentlyPosted(worldId);if(!c)return null;return generateMomentForCharacter(c.id)}
function simulate(worldId,opts={}){tickStatuses(worldId);if(opts.chat!==false&&Math.random()<.75)autonomousChat(worldId);if(opts.moment!==false&&Math.random()<.55)autonomousMoment(worldId)}
window.OCLifeSimulator={simulate,tickStatuses,autonomousChat,autonomousMoment,generateChatById,generateMomentForCharacter};
})();