(function(){
'use strict';
const S=()=>window.OCLifeStore,AI=()=>window.OCLifeAI;const pick=a=>a[Math.floor(Math.random()*a.length)];
const T={activities:['在整理手邊的東西','剛忙完一件事，正在放空','坐著發呆','在吃東西','在看訊息','準備出門','剛回到住處','在處理工作','在做自己的興趣','什麼也沒做，只是休息'],moods:['平靜','放鬆','有點累','心情不錯','專注','有點無聊'],places:['住處','工作地點','街上','咖啡店','房間','附近'],openers:['你在做什麼','剛剛想到一件事','還醒著？','今天過得怎麼樣','我剛忙完','突然有點想找你說話'],replies:['沒什麼，剛好也在想事情','嗯？怎麼突然問這個','還行，你呢','我知道，你一開口我就猜到了','等我一下，馬上回來','說吧，我在聽']};
function chars(worldId){return S().all('characters',{worldId})}function statusOf(id){return S().all('statuses').find(s=>s.characterId===id)}
function tickStatuses(worldId){for(const c of chars(worldId)){const st=statusOf(c.id);if(!st||Math.random()<.58)continue;S().update('statuses',st.id,{place:pick(T.places),activity:pick(T.activities),mood:pick(T.moods),updatedAt:Date.now()})}}
function rel(a,b){return (a.relationshipLinks||[]).find(x=>x.characterId===b.id)||null}
function cfg(){const s=S().data.settings||{};return{provider:s.provider||'none',baseUrl:s.baseUrl||'',apiKey:s.apiKey||'',model:s.model||''}}
function parseJSON(text){let t=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(t)}catch(_){const m=t.match(/\{[\s\S]*\}/);if(m)return JSON.parse(m[0]);throw new Error('AI 對話格式無法解析')}}
function charProfile(c){const ip=c.interactionProfile||{};return`姓名：${c.name}\n身份：${c.identity||'未設定'}\n性格：${c.personality||'未設定'}\n性格底層：${ip.core||''}\n外在表現：${ip.outer||''}\n親密關係中的樣子：${ip.intimate||''}\n情緒反應：${ip.emotionalReactions||''}\n主動性與照顧方式：${ip.initiative||''}\n親密表達：${ip.affection||''}\n說話節奏：${c.speech||ip.speechRhythm||''}\n常用稱呼：${ip.nicknames||''}\n肢體／生活習慣：${c.habits||ip.physicalHabits||''}\n背景：${c.background||''}\n底線：${c.boundaries||''}`}
async function aiChat(worldId,a,b,chat){const c=cfg();if(c.provider==='none'||!c.apiKey||!c.model)throw new Error('AI 未設定');const w=S().get('worlds',worldId),ra=rel(a,b),rb=rel(b,a),sa=statusOf(a.id),sb=statusOf(b.id);const recent=S().all('messages',{chatId:chat.id}).sort((x,y)=>x.at-y.at).slice(-12).map(m=>`${S().get('characters',m.senderId)?.name||'角色'}：${m.text}`).join('\n');const relationType=ra?.type||rb?.type||'未標明';const shared=ra?.sharedFacts||rb?.sharedFacts||'';const intimacy=ra?.intimacyLevel||rb?.intimacyLevel||'';const style=ra?.interactionStyle||rb?.interactionStyle||'';const prompt=`你要模擬兩名OC在自己的世界裡自然聊天。不是客服，不是角色介紹，不是第一次見面。\n\n【世界】\n${w?.name||''}\n${w?.summary||''}\n硬規則：${w?.rules||''}\n\n【角色A】\n${charProfile(a)}\n現在：${sa?.place||''}｜${sa?.activity||''}｜${sa?.mood||''}\n\n【角色B】\n${charProfile(b)}\n現在：${sb?.place||''}｜${sb?.activity||''}｜${sb?.mood||''}\n\n【兩人關係】\n類型：${relationType}\nA看B：${ra?.perspective||''}\nB看A：${rb?.perspective||''}\n共同事實／共同經歷：${shared}\n親密程度：${intimacy}\n固定相處模式：${style}\n\n【最近聊天】\n${recent||'暫無'}\n\n生成4到8則短訊息，像真實聊天軟體。最重要的是讓人一眼看出兩人的熟悉程度與性格差異。\n若關係是情侶／伴侶／已婚／長期戀人：\n- 必須像已經很熟的戀人，禁止「今天過得怎樣」「你喜歡什麼」「可以跟我說說嗎」這類陌生人式試探。\n- 可以自然省略主語、接上共同生活、舊梗、習慣、暱稱、撒嬌、嫌棄、逗弄、照顧、默契；不要每句都甜，也不要突然像偶像劇告白。\n- 他們知道彼此的日常習慣和脾氣，對話可以直接從半截話題開始。\n- 角色的愛意要按照各自性格表現，不要把所有情侶都寫成同一種溫柔。\n- 若資料寫了嘴硬、毒舌、黏人、主導、被動、愛逗人等，必須反映在措辭與節奏，不只在內容中口頭描述。\n所有關係都要避免過度禮貌與解說設定。每則最好1到2句。\n只輸出JSON：{"messages":[{"sender":"角色姓名","text":"訊息"}]}。sender只能是${a.name}或${b.name}。`;
 const out=await AI().call({...c,temperature:.9,maxTokens:1800,messages:[{role:'system',content:'你是高一致性的OC互動模擬器。關係熟悉度與人物性格必須直接體現在語氣、節奏、稱呼和默契裡，而不是只描述設定。'},{role:'user',content:prompt}]});const data=parseJSON(out);return Array.isArray(data.messages)?data.messages:[]}
function localChat(worldId,a,b,chat){const m1=S().add('messages',{chatId:chat.id,worldId,senderId:a.id,text:pick(T.openers),at:Date.now()-3500});const m2=S().add('messages',{chatId:chat.id,worldId,senderId:b.id,text:pick(T.replies),at:Date.now()});S().update('chats',chat.id,{lastAt:Date.now()});return[m1,m2]}
async function autonomousChat(worldId){const list=chars(worldId);if(list.length<2)return null;let pairs=[];for(const a of list)for(const l of (a.relationshipLinks||[])){const b=S().get('characters',l.characterId);if(b&&b.worldId===worldId&&a.id<b.id)pairs.push([a,b])}let a,b;if(pairs.length&&Math.random()<.85)[a,b]=pick(pairs);else{a=pick(list);b=pick(list.filter(x=>x.id!==a.id))}const chat=S().ensureChat(worldId,a.id,b.id);try{const generated=await aiChat(worldId,a,b,chat);if(!generated.length)throw new Error('空回覆');const base=Date.now()-generated.length*900;const made=[];for(let i=0;i<generated.length;i++){const g=generated[i],sender=S().namesEquivalent(g.sender,a.name)?a:S().namesEquivalent(g.sender,b.name)?b:null;if(!sender||!String(g.text||'').trim())continue;made.push(S().add('messages',{chatId:chat.id,worldId,senderId:sender.id,text:String(g.text).trim(),at:base+i*900}))}if(!made.length)throw new Error('沒有有效訊息');S().update('chats',chat.id,{lastAt:Date.now()});window.dispatchEvent(new CustomEvent('oclife:ai-chat-complete',{detail:{worldId,chatId:chat.id}}));return made}catch(e){console.warn('[OC Life] AI chat fallback:',e);return localChat(worldId,a,b,chat)}}
function autonomousMoment(worldId){const list=chars(worldId);if(!list.length)return null;const c=pick(list),st=statusOf(c.id),moment=S().add('moments',{worldId,characterId:c.id,text:pick([`${st?.activity||'今天很安靜'}\n偶爾這樣也不錯`,`今天的狀態：${st?.mood||'平靜'}`,`剛從${st?.place||'外面'}回來`,'沒什麼特別的，只是想留一句','今天有點想偷懶']),at:Date.now(),likes:[],comments:[]});const others=list.filter(x=>x.id!==c.id);if(others.length&&Math.random()<.7){moment.comments.push({id:S().uid('comment'),characterId:pick(others).id,text:pick(['看到了','你倒是挺悠閒','嗯，知道了','晚點聊','這句我記住了']),at:Date.now()+1000});S().save()}return moment}
function simulate(worldId,opts={}){tickStatuses(worldId);if(opts.chat!==false&&Math.random()<.75)autonomousChat(worldId);if(opts.moment!==false&&Math.random()<.55)autonomousMoment(worldId)}
window.addEventListener('oclife:ai-chat-complete',()=>{const t=document.querySelector('#pageTitle')?.textContent;if(t==='聊天')document.querySelector('#worldNav [data-tab="chat"]')?.click()});
window.OCLifeSimulator={simulate,tickStatuses,autonomousChat,autonomousMoment};
})();
