(function(){
'use strict';
const KEY='oclife_v010',MEDIA_DB='oclife_media_v1',MEDIA_STORE='avatars';
const COLLECTIONS=['worlds','characters','statuses','chats','messages','moments','events','ifLines','writings','questions'];
const seed={version:1,settings:{provider:'none',baseUrl:'',apiKey:'',model:'',autoSimulate:true},worlds:[],characters:[],statuses:[],chats:[],messages:[],moments:[],events:[],ifLines:[],writings:[],questions:[]};
const uid=(p='id')=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
const clone=v=>JSON.parse(JSON.stringify(v));
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');const data=raw&&raw.version?Object.assign(clone(seed),raw):clone(seed);for(const k of COLLECTIONS)if(!Array.isArray(data[k]))data[k]=[];return data}catch(_){return clone(seed)}}
let db=load(),lastSaveError=null,mediaReady=false;
function openMediaDB(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('IndexedDB unavailable'));const r=indexedDB.open(MEDIA_DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(MEDIA_STORE))d.createObjectStore(MEDIA_STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('IndexedDB open failed'))})}
async function putAvatar(id,data){if(!id||!data)return;const d=await openMediaDB();await new Promise((resolve,reject)=>{const tx=d.transaction(MEDIA_STORE,'readwrite');tx.objectStore(MEDIA_STORE).put({id,data,updatedAt:Date.now()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});d.close()}
async function getAvatar(id){if(!id)return'';try{const d=await openMediaDB(),out=await new Promise((resolve,reject)=>{const tx=d.transaction(MEDIA_STORE,'readonly'),r=tx.objectStore(MEDIA_STORE).get(id);r.onsuccess=()=>resolve(r.result?.data||'');r.onerror=()=>reject(r.error)});d.close();return out}catch(_){return''}}
async function deleteAvatar(id){try{const d=await openMediaDB();await new Promise((resolve,reject)=>{const tx=d.transaction(MEDIA_STORE,'readwrite');tx.objectStore(MEDIA_STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});d.close()}catch(_){}}
function stripHeavy(value){if(Array.isArray(value))return value.map(stripHeavy);if(value&&typeof value==='object'){const out={};for(const[k,v]of Object.entries(value)){if(k==='avatarData')continue;out[k]=stripHeavy(v)}return out}return value}
function jsonSize(value){try{return new Blob([JSON.stringify(value)]).size}catch(_){return 0}}
function isQuotaError(e){return !!(e&&(e.name==='QuotaExceededError'||e.code===22||e.code===1014||/quota.*exceed/i.test(String(e.message||''))))}
async function persistCurrentAvatars(){const jobs=[];for(const c of db.characters||[])if(c?.id&&c.avatarData)jobs.push(putAvatar(c.id,c.avatarData));await Promise.allSettled(jobs)}
function save(){const slim=stripHeavy(db);try{localStorage.setItem(KEY,JSON.stringify(slim));lastSaveError=null;persistCurrentAvatars();window.dispatchEvent(new CustomEvent('oclife:change'));return true}catch(e){lastSaveError=e;console.error('[OC Life] local save failed',e);const err=new Error(isQuotaError(e)?'本機儲存空間已滿，請等待圖片資料搬移完成後再試':'本機資料儲存失敗：'+(e?.message||e));err.name=e?.name||'StorageError';err.storage=true;err.quota=isQuotaError(e);throw err}}
async function hydrateMedia(){let changed=false;for(const c of db.characters||[]){if(c.avatarData){putAvatar(c.id,c.avatarData);continue}const data=await getAvatar(c.id);if(data){c.avatarData=data;changed=true}}mediaReady=true;if(changed)window.dispatchEvent(new CustomEvent('oclife:media-ready'));return changed}
function storageInfo(){const raw=localStorage.getItem(KEY)||'';const memoryBytes=jsonSize(db),persistedBytes=new Blob([raw]).size,avatarBytes=(db.characters||[]).reduce((n,c)=>n+String(c.avatarData||'').length,0);return{memoryBytes,persistedBytes,avatarBytes,mediaReady,lastSaveError:lastSaveError?.message||'',characters:(db.characters||[]).length}}
function compactNow(){persistCurrentAvatars();const slim=stripHeavy(db);localStorage.setItem(KEY,JSON.stringify(slim));lastSaveError=null;window.dispatchEvent(new CustomEvent('oclife:storage-compacted',{detail:storageInfo()}));return storageInfo()}
function all(type,filter={}){return(db[type]||[]).filter(x=>Object.entries(filter).every(([k,v])=>x[k]===v))}
function get(type,id){return(db[type]||[]).find(x=>x.id===id)||null}
function add(type,obj){if(!Array.isArray(db[type]))db[type]=[];const item={id:obj.id||uid(type.slice(0,-1)),createdAt:Date.now(),...obj};db[type].push(item);save();return item}
function update(type,id,patch){const item=get(type,id);if(!item)return null;Object.assign(item,patch,{updatedAt:Date.now()});save();return item}
function remove(type,id){if(type==='characters')deleteAvatar(id);db[type]=(db[type]||[]).filter(x=>x.id!==id);save()}
const VARIANT_PAIRS=['蕭萧','鴦鸯','鴛鸳','麗丽','龍龙','風风','雲云','葉叶','劉刘','陳陈','張张','趙赵','錢钱','孫孙','吳吴','鄭郑','馮冯','衛卫','蔣蒋','韓韩','楊杨','謝谢','蘇苏','羅罗','鐘钟','鍾钟','顧顾','許许','鄧邓','鄒邹','盧卢','賈贾','賴赖','龔龚','嚴严','喬乔','闕阙','閻阎','簡简','萬万','樂乐','鄺邝','譚谭','黃黄','藍蓝','綠绿','紅红','夢梦','靈灵','曉晓','陽阳','陰阴','愛爱','戀恋','歡欢','憂忧','寧宁','靜静','華华','國国','東东','門门','馬马','鳥鸟','魚鱼','貓猫','劍剑','獵猎','騎骑','車车','賽赛','場场','隊队','醫医','師师','學学','會会','長长','頭头','體体','關关','係系','親亲','敵敌','對对','與与','為为','從从','這这','個个','們们','裡里','時时','間间','開开','發发','現现','實实','進进','過过','後后','還还','說说','話话','點点','應应','該该'];
const toSimpleMap=new Map();for(const pair of VARIANT_PAIRS){const a=[...pair];if(a.length>=2)toSimpleMap.set(a[0],a[1])}
function basicName(value){return String(value??'').normalize('NFKC').trim().toLowerCase().replace(/[\s·・•‧._\-—–'"「」『』【】()（）\[\]{}]/g,'')}
function canonicalName(value){const raw=basicName(value);return[...raw].map(ch=>toSimpleMap.get(ch)||ch).join('')}
const collators=[new Intl.Collator('zh-Hans',{usage:'search',sensitivity:'base'}),new Intl.Collator('zh-Hant',{usage:'search',sensitivity:'base'})];
function namesEquivalent(a,b){const x=basicName(a),y=basicName(b);if(!x||!y)return false;if(x===y||canonicalName(x)===canonicalName(y))return true;try{return collators.some(c=>c.compare(x,y)===0)}catch(_){return false}}
function findCharacterByName(worldId,name){return all('characters',{worldId}).find(c=>namesEquivalent(c.name,name))||null}
function emptyValue(v){if(v==null)return true;if(typeof v==='string')return v.trim()==='';if(Array.isArray(v))return v.length===0;if(typeof v==='object')return Object.keys(v).length===0;return false}
function mergeEmpty(existing,input){const patch={};for(const[k,v]of Object.entries(input||{})){if(['id','createdAt','updatedAt','worldId','name'].includes(k))continue;if(emptyValue(existing[k])&&!emptyValue(v))patch[k]=v}return patch}
function createWorld(input){return add('worlds',{name:input.name||'未命名世界',emoji:input.emoji||'✦',summary:input.summary||'',era:input.era||'',location:input.location||'',rules:input.rules||'',tone:input.tone||''})}
function createCharacter(input){const worldId=input.worldId,name=input.name||'未命名角色',existing=worldId?findCharacterByName(worldId,name):null;if(existing){const patch=mergeEmpty(existing,input);if(Object.keys(patch).length)update('characters',existing.id,patch);return get('characters',existing.id)}const c=add('characters',{worldId,name,emoji:input.emoji||'◉',gender:input.gender||'',age:input.age||'',appearance:input.appearance||'',personality:input.personality||'',identity:input.identity||'',speech:input.speech||'',relationships:input.relationships||'',habits:input.habits||'',background:input.background||'',abilities:input.abilities||'',boundaries:input.boundaries||'',notes:input.notes||'',avatarData:input.avatarData||'',interactionProfile:input.interactionProfile||{},relationshipLinks:Array.isArray(input.relationshipLinks)?input.relationshipLinks:[]});add('statuses',{worldId:c.worldId,characterId:c.id,place:'未設定',activity:'正在休息',mood:'平靜',withIds:[],updatedAt:Date.now()});return c}
function ensureChat(worldId,aId,bId){const ids=[aId,bId].sort();let chat=db.chats.find(c=>c.worldId===worldId&&c.memberIds.length===2&&[...c.memberIds].sort().join('|')===ids.join('|'));if(!chat)chat=add('chats',{worldId,memberIds:ids,title:'',lastAt:0});return chat}
function deleteWorld(worldId){const charIds=all('characters',{worldId}).map(x=>x.id),chatIds=all('chats',{worldId}).map(x=>x.id);charIds.forEach(deleteAvatar);db.worlds=db.worlds.filter(x=>x.worldId!==worldId&&x.id!==worldId);db.characters=db.characters.filter(x=>x.worldId!==worldId);db.statuses=db.statuses.filter(x=>x.worldId!==worldId);db.chats=db.chats.filter(x=>x.worldId!==worldId);db.messages=db.messages.filter(x=>!chatIds.includes(x.chatId));db.moments=db.moments.filter(x=>x.worldId!==worldId);db.events=db.events.filter(x=>x.worldId!==worldId);db.ifLines=db.ifLines.filter(x=>x.worldId!==worldId);db.writings=db.writings.filter(x=>x.worldId!==worldId);db.questions=db.questions.filter(x=>x.worldId!==worldId);save()}
function exportData(){return new Blob([JSON.stringify(db,null,2)],{type:'application/json'})}
function importData(obj){if(!obj||!Array.isArray(obj.worlds)||!Array.isArray(obj.characters))throw new Error('不是有效的 OC Life 備份');db=Object.assign(clone(seed),obj,{version:1});for(const k of COLLECTIONS)if(!Array.isArray(db[k]))db[k]=[];save();persistCurrentAvatars();hydrateMedia()}
window.OCLifeStore={uid,all,get,add,update,remove,createWorld,createCharacter,ensureChat,deleteWorld,exportData,importData,canonicalName,namesEquivalent,findCharacterByName,mergeEmpty,storageInfo,compactNow,hydrateMedia,getAvatar,putAvatar,get data(){return db},save,get mediaReady(){return mediaReady}};
setTimeout(()=>{hydrateMedia();try{compactNow()}catch(e){console.warn('[OC Life] initial storage compact failed',e)}},60);
})();