(function(){
'use strict';
const CURRENT='20260812-1',KEY='oclife_update_settings_v1',ATTEMPT_KEY='oclife_update_attempt_v1';
let checking=false,reloading=false,lastCheck=0;
function settings(){try{return{auto:true,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(_){return{auto:true}}}
function save(patch){localStorage.setItem(KEY,JSON.stringify({...settings(),...patch}))}
function attempt(){try{return JSON.parse(localStorage.getItem(ATTEMPT_KEY)||'null')}catch(_){return null}}
function markAttempt(version){try{localStorage.setItem(ATTEMPT_KEY,JSON.stringify({version,at:Date.now()}))}catch(_){}}
function recentlyAttempted(version){const a=attempt();return !!(a&&a.version===version&&Date.now()-Number(a.at||0)<60000)}
function manifestUrl(){const u=new URL('./version.json',location.href);u.searchParams.set('_t',String(Date.now()));return u.href}
async function latest(){const r=await fetch(manifestUrl(),{cache:'no-store',headers:{'Cache-Control':'no-cache','Pragma':'no-cache'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(!d?.version)throw new Error('版本資料缺少 version');return d}
async function purge(){const jobs=[];try{if('caches'in window)jobs.push(caches.keys().then(keys=>Promise.all(keys.map(k=>caches.delete(k)))))}catch(_){}try{if(navigator.serviceWorker?.getRegistrations)jobs.push(navigator.serviceWorker.getRegistrations().then(rs=>Promise.all(rs.map(r=>r.unregister()))))}catch(_){}await Promise.allSettled(jobs)}
function overlay(version,text='正在強制載入最新版…'){document.getElementById('ocUpdateOverlay')?.remove();const el=document.createElement('div');el.id='ocUpdateOverlay';el.innerHTML=`<style>#ocUpdateOverlay{position:fixed;inset:0;z-index:30000;background:rgba(3,8,21,.96);display:grid;place-items:center;color:#dcecff;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.ocu-box{width:min(340px,82vw)}.ocu-code{font-size:9px;letter-spacing:.16em;color:#5d91cf;margin-bottom:13px}.ocu-title{font:700 18px system-ui,sans-serif;color:#f1f7ff;margin-bottom:7px}.ocu-text{font-size:10px;color:#7791b2;line-height:1.6}.ocu-track{height:2px;background:#12233e;margin-top:16px;overflow:hidden}.ocu-bar{height:100%;background:linear-gradient(90deg,#2c71ff,#63dcff);animation:ocuLoad .8s ease infinite}@keyframes ocuLoad{0%{width:0;margin-left:0}60%{width:70%;margin-left:15%}100%{width:0;margin-left:100%}}</style><div class="ocu-box"><div class="ocu-code">SYSTEM UPDATE // BUILD ${version}</div><div class="ocu-title">${text}</div><div class="ocu-text">正在清除舊快取並重新連線。角色、世界、聊天與 API 設定不會被刪除。</div><div class="ocu-track"><div class="ocu-bar"></div></div></div>`;document.body.appendChild(el);return el}
async function reloadTo(version,{force=false}={}){if(reloading)return;reloading=true;markAttempt(version);overlay(version,force?'正在強制重新載入最新版…':'偵測到新版本，正在自動更新…');try{await purge()}catch(_){}const u=new URL(location.href);u.searchParams.set('build',version);u.searchParams.set('_reload',String(Date.now()));setTimeout(()=>location.replace(u.href),120)}
async function check({manual=false,force=false}={}){if(checking||reloading)return null;checking=true;lastCheck=Date.now();const status=document.getElementById('ocUpdateStatus');if(status)status.textContent='正在檢查更新…';try{const d=await latest(),different=String(d.version)!==CURRENT;if(force){await reloadTo(d.version||CURRENT,{force:true});return d}if(different&&settings().auto){if(recentlyAttempted(d.version)){if(status)status.textContent=`版本 ${d.version} 正在部署，稍後會再檢查`;return d}await reloadTo(d.version);return d}if(status)status.textContent=different?`發現新版本 ${d.version}`:`已是最新版 ${CURRENT}`;if(manual)window.OCLifeAutoLife?.toast?.(different?`發現新版本 ${d.version}`:`✓ 已是最新版 ${CURRENT}`);return d}catch(e){if(status)status.textContent='檢查失敗：'+(e?.message||e);if(manual)window.OCLifeAutoLife?.toast?.(`檢查更新失敗：${e?.message||e}`,{error:true});return null}finally{checking=false}}
function forceReload(){return check({manual:true,force:true}).catch(()=>reloadTo(CURRENT,{force:true}))}
function injectSettings(){const modal=document.querySelector('#modalRoot .modal');if(!modal||modal.dataset.updateManager||modal.querySelector('h2')?.textContent!=='設定')return;modal.dataset.updateManager='1';const actions=modal.querySelector('.actions'),box=document.createElement('div'),s=settings();box.innerHTML=`<div style="margin:16px 0;padding:12px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.28)"><b style="font-size:13px">版本與更新</b><div class="note">目前版本：${CURRENT}</div><label style="display:block;margin-top:8px"><input type="checkbox" id="ocAutoUpdate" ${s.auto?'checked':''}> 強制自動更新到最新版</label><div class="note">偵測到新版本時會清除舊快取並自動重新載入，避免 Safari 一直使用舊程式。</div><div class="toolbar" style="margin-top:9px"><button type="button" class="secondary" id="ocCheckUpdate">檢查更新</button><button type="button" class="secondary" id="ocForceUpdate">強制載入最新版</button></div><div class="note" id="ocUpdateStatus"></div></div>`;actions?.before(box.firstElementChild);modal.querySelector('#ocAutoUpdate').onchange=e=>save({auto:e.target.checked});modal.querySelector('#ocCheckUpdate').onclick=()=>check({manual:true});modal.querySelector('#ocForceUpdate').onclick=forceReload}
function install(){new MutationObserver(injectSettings).observe(document.documentElement,{childList:true,subtree:true});injectSettings();setTimeout(()=>check(),1800);setInterval(()=>{if(settings().auto&&document.visibilityState!=='hidden')check()},180000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&settings().auto&&Date.now()-lastCheck>60000)check()})}
window.OCLifeUpdateManager={version:'1.0.1',build:CURRENT,settings,save,check,forceReload,reloadTo};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();
})();