(function(){
'use strict';
const S=window.OCLifeStore,AI=window.OCLifeAI,clean=v=>String(v??'').trim(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cfg(){const s=S.data.settings||{};return{provider:s.provider||'none',baseUrl:s.baseUrl||'',apiKey:s.apiKey||'',model:s.model||''}}
function wid(){return window.OCLifeWorldContext?.get?.()||window.OCLifePhone?.activeWorldId||null}
function profile(c){const ip=c.interactionProfile||{};return`【${c.name}】\n身份：${c.identity||''}\n外貌：${c.appearance||''}\n性格：${c.personality||''}\n性格核心：${ip.core||''}\n親密時：${ip.intimate||''}\n說話方式：${c.speech||ip.speechRhythm||''}\n背景：${c.background||''}\n能力：${c.abilities||''}\n底線：${c.boundaries||''}\n關係：${c.relationships||''}`}
function modal(html){const r=document.querySelector('#modalRoot');r.innerHTML=`<div class="modal-bg"><div class="modal oc-writing-modal">${html}</div></div>`;r.querySelector('.modal-bg').onclick=e=>{if(e.target===e.currentTarget)r.innerHTML=''}}
function style(){if(document.getElementById('oc-writing-style'))return;const s=document.createElement('style');s.id='oc-writing-style';s.textContent=`.oc-writing-modal{max-height:92vh}.oc-writing-result{white-space:pre-wrap;line-height:1.8;background:#fff;border:1px solid var(--line);border-radius:16px;padding:14px;min-height:180px}.oc-writing-tabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:12px}.oc-writing-tabs button.active{background:var(--accent);color:#fff}.oc-writing-launch{position:fixed;right:18px;bottom:calc(92px + env(safe-area-inset-bottom));z-index:45;border:0;border-radius:18px;padding:12px 15px;background:#fffdf9;box-shadow:0 10px 28px #0002;font-weight:800}`;document.head.appendChild(s)}
function charsText(worldId,ids){const cs=S.all('characters',{worldId});const chosen=ids?.length?cs.filter(c=>ids.includes(c.id)):cs;return chosen.map(profile).join('\n\n')}
async function call(mode,source,instruction,ids,length){const worldId=wid(),w=S.get('worlds',worldId),c=cfg();if(!worldId)throw new Error('請先進入世界');if(c.provider==='none'||!c.apiKey||!c.model)throw new Error('請先設定 AI');const people=charsText(worldId,ids);let prompt='';if(mode==='short')prompt=`你是OC短篇小說寫作者。根據以下世界與角色寫一篇完整短文。\n【世界】${w?.name||''}\n${w?.summary||''}\n硬規則：${w?.rules||''}\n【角色】\n${people}\n【使用者想寫的內容／情境】\n${source}\n【額外要求】${instruction||'無'}\n目標長度：約${length}字。角色必須符合人設與關係，不要把聊天介面的“禁止動作描寫”規則套到小說；小說可以正常寫敘事、動作、環境與心理。不要擅自改變重大主線設定。只輸出正文。`;
else prompt=`你是OC主線補充寫作者。使用者會提供自己已寫好的主線原文。你的任務不是重寫原文，而是沿著原文的事實、語氣、人物關係和事件順序，補出原文沒有明說但可以自然成立的細節與後續。\n【世界】${w?.name||''}\n${w?.summary||''}\n硬規則：${w?.rules||''}\n【角色】\n${people}\n【主線原文——最高優先級，不可推翻或偷偷修改】\n${source}\n【希望補充的方向】${instruction||'由你從原文可延伸處自然補充'}\n規則：1. 原文已明說的事實全部保留；2. 不把推測寫成與原文衝突的新設定；3. 主要新增原文留白中的原因、過程、情緒、過渡、後續反應、小事件或可合理延伸的情節；4. 若原文沒有足夠依據決定重大設定，保持模糊，不擅自定死；5. 續寫要接得上原文，而不是摘要原文。目標約${length}字。只輸出補充／續寫正文。`;
return AI.call({...c,temperature:mode==='short'?.9:.72,maxTokens:Math.max(1500,Math.ceil(Number(length||1200)*1.8)),messages:[{role:'system',content:mode==='short'?'忠實角色設定的小說寫作者。':'尊重使用者原文、只在留白處補充的主線續寫助手。'},{role:'user',content:prompt}]})}
function open(defaultMode='short'){style();const worldId=wid(),cs=S.all('characters',{worldId});let mode=defaultMode;modal(`<h2>寫作</h2><div class="oc-writing-tabs"><button class="secondary ${mode==='short'?'active':''}" data-mode="short">短文寫作</button><button class="secondary ${mode==='canon'?'active':''}" data-mode="canon">主線補充</button></div><p class="note" id="writeHint"></p><div class="field"><label id="sourceLabel"></label><textarea id="writeSource" style="min-height:150px"></textarea></div><div class="field"><label>使用角色</label><div>${cs.map(c=>`<label style="display:inline-flex;gap:5px;margin:4px 10px 4px 0"><input type="checkbox" data-write-char value="${c.id}" checked>${esc(c.name)}</label>`).join('')}</div></div><div class="field"><label>額外要求／想補充的方向</label><textarea id="writeInstruction"></textarea></div><div class="field"><label>大約字數</label><input id="writeLength" type="number" min="200" max="8000" value="1200"></div><div class="toolbar"><button class="primary" id="writeGenerate">生成</button><button class="secondary hidden" id="writeCopy">複製結果</button></div><div id="writeStatus" class="note"></div><div id="writeResult" class="oc-writing-result hidden"></div>`);
function labels(){document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));document.querySelector('#sourceLabel').textContent=mode==='short'?'想寫的情境／梗概':'你的主線原文';document.querySelector('#writeHint').textContent=mode==='short'?'依照世界觀與角色設定生成完整短篇；小說模式允許正常的動作、環境與心理描寫。':'AI 會把你的原文視為最高優先級，只在原文沒有寫明的地方補充與續寫，不擅自推翻原設定。'}labels();document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;labels()});document.querySelector('#writeGenerate').onclick=async()=>{const src=clean(document.querySelector('#writeSource').value);if(!src)return alert(mode==='short'?'先寫一點情境或梗概':'請貼上主線原文');const btn=document.querySelector('#writeGenerate'),st=document.querySelector('#writeStatus'),res=document.querySelector('#writeResult'),ids=[...document.querySelectorAll('[data-write-char]:checked')].map(x=>x.value);btn.disabled=true;st.textContent=mode==='short'?'正在寫短文…':'正在依照原文補充主線…';try{const text=await call(mode,src,clean(document.querySelector('#writeInstruction').value),ids,document.querySelector('#writeLength').value);res.textContent=clean(text);res.classList.remove('hidden');document.querySelector('#writeCopy').classList.remove('hidden');st.textContent='✓ 生成完成'}catch(e){st.textContent='生成失敗：'+(e?.message||e)}finally{btn.disabled=false}};document.querySelector('#writeCopy').onclick=async()=>{await navigator.clipboard.writeText(document.querySelector('#writeResult').textContent);document.querySelector('#writeStatus').textContent='✓ 已複製'}}
function install(){style();if(document.getElementById('ocWritingLaunch'))return;const b=document.createElement('button');b.id='ocWritingLaunch';b.className='oc-writing-launch';b.textContent='✎ 寫作';b.onclick=()=>open('short');document.body.appendChild(b)}
window.OCLifeWritingStudio={open,generate:call};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();
})();